/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Logs;

import Classes.Acesso.LogErroAcesso;
import Classes.DAO.LogDAO;
import Classes.DAO.LoginDAO;
import Classes.Util.DataHora;
import Frm.Preparo.FrmImprimirPedidoPreparo;
import Classes.Modelo.Log;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public class FrmLogErro extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public FrmLogErro() {
        initComponents();
        setTitle("Log Erros");
        readLogErro();
        readLoginLogout();
        LogErroAcesso Acesso = new LogErroAcesso();
        Acesso.verificarAcessoLogErro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAtualizar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnImprimirRelatorio = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogErro = new javax.swing.JTable();
        txtPesquisarErros = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoginLogout = new javax.swing.JTable();
        txtPesquisarLoginLogout = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setFocusable(false);
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAtualizar);
        jToolBar1.add(jSeparator6);

        btnImprimirRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_print.png"))); // NOI18N
        btnImprimirRelatorio.setText("Imprimir");
        btnImprimirRelatorio.setFocusable(false);
        btnImprimirRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirRelatorio.setPreferredSize(new java.awt.Dimension(60, 60));
        btnImprimirRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatorioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirRelatorio);

        tblLogErro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Classe", "Erros", "Data", "Usuário", "Computador / Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLogErro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblLogErro);
        if (tblLogErro.getColumnModel().getColumnCount() > 0) {
            tblLogErro.getColumnModel().getColumn(0).setMinWidth(50);
            tblLogErro.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblLogErro.getColumnModel().getColumn(0).setMaxWidth(50);
            tblLogErro.getColumnModel().getColumn(1).setMinWidth(150);
            tblLogErro.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblLogErro.getColumnModel().getColumn(1).setMaxWidth(150);
            tblLogErro.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblLogErro.getColumnModel().getColumn(3).setPreferredWidth(500);
            tblLogErro.getColumnModel().getColumn(4).setMinWidth(150);
            tblLogErro.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblLogErro.getColumnModel().getColumn(4).setMaxWidth(150);
            tblLogErro.getColumnModel().getColumn(5).setMinWidth(150);
            tblLogErro.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblLogErro.getColumnModel().getColumn(5).setMaxWidth(150);
            tblLogErro.getColumnModel().getColumn(6).setPreferredWidth(250);
        }

        txtPesquisarErros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarErrosKeyReleased(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarErros)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarErros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jTabbedPane1.addTab("Erros", jPanel1);

        tblLoginLogout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Status", "Data", "Usuário", "Computador / Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLoginLogout);
        if (tblLoginLogout.getColumnModel().getColumnCount() > 0) {
            tblLoginLogout.getColumnModel().getColumn(0).setMinWidth(50);
            tblLoginLogout.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblLoginLogout.getColumnModel().getColumn(0).setMaxWidth(50);
            tblLoginLogout.getColumnModel().getColumn(1).setMinWidth(150);
            tblLoginLogout.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblLoginLogout.getColumnModel().getColumn(1).setMaxWidth(150);
            tblLoginLogout.getColumnModel().getColumn(2).setMinWidth(150);
            tblLoginLogout.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblLoginLogout.getColumnModel().getColumn(2).setMaxWidth(150);
            tblLoginLogout.getColumnModel().getColumn(3).setMinWidth(150);
            tblLoginLogout.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblLoginLogout.getColumnModel().getColumn(3).setMaxWidth(150);
            tblLoginLogout.getColumnModel().getColumn(4).setPreferredWidth(250);
        }

        txtPesquisarLoginLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarLoginLogoutKeyReleased(evt);
            }
        });

        jLabel2.setText("Pesquisar:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarLoginLogout)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarLoginLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Login / Logout", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarErrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarErrosKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblLogErro.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblLogErro.setRowSorter(sorter);
        String text = txtPesquisarErros.getText().trim();
        String parametro = "*";
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text.toUpperCase()));
        }
    }//GEN-LAST:event_txtPesquisarErrosKeyReleased

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        readLogErro();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnImprimirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatorioActionPerformed
        FrmImprimirPedidoPreparo frm = new FrmImprimirPedidoPreparo(null, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btnImprimirRelatorioActionPerformed

    private void txtPesquisarLoginLogoutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarLoginLogoutKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblLoginLogout.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblLoginLogout.setRowSorter(sorter);
        String text = txtPesquisarLoginLogout.getText().trim();
        String parametro = "*";
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text.toUpperCase()));
        }
    }//GEN-LAST:event_txtPesquisarLoginLogoutKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    public static javax.swing.JButton btnImprimirRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblLogErro;
    private javax.swing.JTable tblLoginLogout;
    private javax.swing.JTextField txtPesquisarErros;
    private javax.swing.JTextField txtPesquisarLoginLogout;
    // End of variables declaration//GEN-END:variables

    private void readLogErro() {
        DefaultTableModel model = (DefaultTableModel) tblLogErro.getModel();
        LogDAO logDao = new LogDAO();
        model.setNumRows(0);
        for (Log log : logDao.readLogErro()) {
            model.addRow(new Object[]{
                log.getLog_id(),
                log.getTipo(),
                log.getClasse(),
                log.getErro(),
                DataHora.getStringDateTime(log.getData()),
                log.getUser(),
                log.getComputador() + " / " + log.getUser_computador()
            });
        }
    }
    
    private void readLoginLogout() {
        DefaultTableModel model = (DefaultTableModel) tblLoginLogout.getModel();
        LoginDAO loginDao = new LoginDAO();
        model.setNumRows(0);
        for (Log log : loginDao.readLogLoginLogout()) {
            model.addRow(new Object[]{
                log.getLog_id(),
                log.getStatus(),
                DataHora.getStringDateTime(log.getData()),
                log.getUser(),
                log.getComputador() + " / " + log.getUser_computador()
            });
        }
    }

}
