/*
 * Copyright (C) 2018 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Recepcao;

import Classes.DAO.LoteAcompanhamentoDAO;
import Classes.DAO.LoteDAO;
import Frm.Login.FrmSalvar;
import Frm.Login.FrmUsuarioSalvar;
import Classes.Modelo.Lote;
import Classes.Modelo.LoteAcompanhamento;
import Classes.Modelo.Usuario;
import Classes.Util.DataHora;
import java.awt.Cursor;
import java.util.Date;

/**
 *
 * @author rafael.lopes
 */
public class FrmConfirmarRetiradaProduto extends javax.swing.JDialog {
    
    private Integer acomp_id;

    /**
     * Creates new form FrmCadastroRetirada
     */
    public FrmConfirmarRetiradaProduto(java.awt.Frame parent, boolean modal, Integer id, Boolean retidado) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        acomp_id = id;
        if (retidado) {
            btnDevolver.setEnabled(true);
            btnRetirar.setEnabled(false);
        }else{
            btnDevolver.setEnabled(false);
            btnRetirar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetirar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnRetirar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_retirar.png"))); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRetirar.setIconTextGap(50);
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnDevolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_devolver.png"))); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDevolver.setIconTextGap(50);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        Usuario user = new Usuario();
        FrmUsuarioSalvar frm = new FrmUsuarioSalvar(null, true, user);
        frm.setVisible(true);
        if (FrmUsuarioSalvar.senha()) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            user.setUser(user.getUser());
            retirarLoteAcompanhamento(user);
            dispose();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        FrmSalvar frmSalvar = new FrmSalvar(null, true);
        frmSalvar.setVisible(true);
        if (FrmSalvar.senha()) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            devolverLoteAcompanhamento();
            dispose();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmarRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmarRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmarRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmarRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmConfirmarRetiradaProduto dialog = new FrmConfirmarRetiradaProduto(new javax.swing.JFrame(), true, null, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalise;
    private javax.swing.JButton btnAnalise1;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnRetirar;
    // End of variables declaration//GEN-END:variables

    private void retirarLoteAcompanhamento(Usuario user) {
        LoteAcompanhamento loteacomp = new LoteAcompanhamento();
        LoteAcompanhamentoDAO loteacompDAO = new LoteAcompanhamentoDAO();
        Lote lote = new Lote();
        LoteDAO loteDAO = new LoteDAO();
        lote.setLote_status("Em Análise");
        loteacomp.setLote_acompanhamento_id(acomp_id);
        loteacomp.setData_retirada(DataHora.getTimestampDate(new Date()));
        loteacomp.setUser_retirada(user);
        loteacompDAO.updateRetiradaLoteAcompanhamento(loteacomp);
        loteDAO.updateLoteStatus(lote);
    }
    
    private void devolverLoteAcompanhamento() {
        LoteAcompanhamento loteacomp = new LoteAcompanhamento();
        LoteAcompanhamentoDAO loteacompDAO = new LoteAcompanhamentoDAO();
        loteacomp.setLote_acompanhamento_id(acomp_id);
        loteacompDAO.updateDevolverLoteAcompanhamento(loteacomp);
    }
    
}
