/*
 * Copyright (C) 2018 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Recepcao;

import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmCadastroRetirada extends javax.swing.JDialog {

    Thread t1;

    /**
     * Creates new form FrmCadastroRetirada
     */
    public FrmCadastroRetirada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pnlRA.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvarCadastroProduto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCodigoBarras = new javax.swing.JTable();
        btnAdicionarCodigo = new javax.swing.JButton();
        btnRemoverCodigo = new javax.swing.JButton();
        pnlRA = new javax.swing.JPanel();
        txtCodigoBarras = new javax.swing.JTextField();
        btnInserirCodigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalvarCadastroProduto.setText("Ok");
        btnSalvarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroProdutoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblCodigoBarras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Página", "Código Barras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCodigoBarras);
        if (tblCodigoBarras.getColumnModel().getColumnCount() > 0) {
            tblCodigoBarras.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblCodigoBarras.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnAdicionarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdicionarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCodigoActionPerformed(evt);
            }
        });

        btnRemoverCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnRemoverCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCodigoActionPerformed(evt);
            }
        });

        pnlRA.setBorder(javax.swing.BorderFactory.createTitledBorder("Documento"));

        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyReleased(evt);
            }
        });

        btnInserirCodigo.setText("Ok");
        btnInserirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRALayout = new javax.swing.GroupLayout(pnlRA);
        pnlRA.setLayout(pnlRALayout);
        pnlRALayout.setHorizontalGroup(
            pnlRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCodigoBarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserirCodigo)
                .addContainerGap())
        );
        pnlRALayout.setVerticalGroup(
            pnlRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnInserirCodigo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 222, Short.MAX_VALUE)
                        .addComponent(btnSalvarCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 227, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastroProduto)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCodigoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        pnlRA.setVisible(true);
        btnAdicionarCodigo.setEnabled(false);
        btnRemoverCodigo.setEnabled(false);
        txtCodigoBarras.requestFocus();
    }//GEN-LAST:event_btnAdicionarCodigoActionPerformed

    private void btnRemoverCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCodigoActionPerformed
        if (tblCodigoBarras.getSelectedRow() != -1) {
            if (tblCodigoBarras.getSelectedRow() == tblCodigoBarras.getRowCount() - 1) {
                DefaultTableModel model = (DefaultTableModel) tblCodigoBarras.getModel();
                model.removeRow(tblCodigoBarras.getSelectedRow());
            } else {
                JOptionPane.showMessageDialog(null, "Não é possivel excluir essa linha");
            }
        }
    }//GEN-LAST:event_btnRemoverCodigoActionPerformed

    private void btnSalvarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroProdutoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        int rows = tblCodigoBarras.getRowCount();
        try {
            if (rows <= 0) {
                JOptionPane.showMessageDialog(null, "Cadastrar o Código de Barras!");
            } else {
                for (int row = 0; row < rows; row++) {
                    criarCadastro((Integer) tblCodigoBarras.getValueAt(row, 0),
                            (Integer) tblCodigoBarras.getValueAt(row, 1));
                }
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel salvar. Algum Campo está inválido!");
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSalvarCadastroProdutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificarCodigo();
        }
    }//GEN-LAST:event_txtCodigoBarrasKeyReleased

    private void btnInserirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCodigoActionPerformed
        verificarCodigo();
    }//GEN-LAST:event_btnInserirCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCadastroRetirada dialog = new FrmCadastroRetirada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCodigo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserirCodigo;
    private javax.swing.JButton btnRemoverCodigo;
    public static javax.swing.JButton btnSalvarCadastroProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlRA;
    private javax.swing.JTable tblCodigoBarras;
    private javax.swing.JTextField txtCodigoBarras;
    // End of variables declaration//GEN-END:variables

    private void verificarCodigo() {
        String in = txtCodigoBarras.getText();
        in = in.replaceFirst("^0+(?!$)", "");
        DefaultTableModel model = (DefaultTableModel) tblCodigoBarras.getModel();
        int rows = tblCodigoBarras.getRowCount();
        for (int row = 0; row < rows; row++) {
            if (in.equals(tblCodigoBarras.getValueAt(row, 1).toString())) {
                pnlRA.setVisible(false);
                btnAdicionarCodigo.setEnabled(true);
                btnRemoverCodigo.setEnabled(true);
                txtCodigoBarras.setText(null);
                JOptionPane.showMessageDialog(null, "Código já adicionado!");
                return;
            }
        }
        if (!txtCodigoBarras.getText().isEmpty()) {
            model.addRow(new Object[]{
                rows + 1,
                in
            });
        }
        pnlRA.setVisible(false);
        btnAdicionarCodigo.setEnabled(true);
        btnRemoverCodigo.setEnabled(true);
        txtCodigoBarras.setText(null);
    }

    private void criarCadastro(int pagina, int codigo_barras) {

    }

}
