/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Recepcao;

import Frm.Preparo.*;
import static Frm.Principal.FrmPrincipal.desktopPane;
import Classes.Util.Frames;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael.lopes
 */
public class FrmMenuEntrada extends javax.swing.JDialog {

    private FrmEntradaProduto EntradaProduto;
    private FrmEntradaValidacaoLimpeza EntradaValidacaoLimpeza;
    private FrmEntradaValidacaoProcesso EntradaValidacaoProcesso;
    private FrmEntradaEEPIG EntradaEEPIG;
    private FrmEntradaDevolucao EntradaDevolucao;

    /**
     * Creates new form FrmAtividades
     */
    public FrmMenuEntrada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Registro de Entrada");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnProduto = new javax.swing.JButton();
        btnValidacaoProcessos = new javax.swing.JButton();
        btnEepig = new javax.swing.JButton();
        btnDevolucao = new javax.swing.JButton();
        btnValidacaoLimpeza = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_pilula.png"))); // NOI18N
        btnProduto.setText("Produto");
        btnProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProduto.setIconTextGap(50);
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        btnValidacaoProcessos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnValidacaoProcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_processo.png"))); // NOI18N
        btnValidacaoProcessos.setText("Validação de Processos");
        btnValidacaoProcessos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnValidacaoProcessos.setIconTextGap(50);
        btnValidacaoProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidacaoProcessosActionPerformed(evt);
            }
        });

        btnEepig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEepig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_EEPIG.png"))); // NOI18N
        btnEepig.setText("EEPIG");
        btnEepig.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEepig.setIconTextGap(50);
        btnEepig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEepigActionPerformed(evt);
            }
        });

        btnDevolucao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDevolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_devolver.png"))); // NOI18N
        btnDevolucao.setText("Devoluções");
        btnDevolucao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDevolucao.setIconTextGap(50);
        btnDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucaoActionPerformed(evt);
            }
        });

        btnValidacaoLimpeza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnValidacaoLimpeza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limpeza.png"))); // NOI18N
        btnValidacaoLimpeza.setText("Validação de Limpeza");
        btnValidacaoLimpeza.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnValidacaoLimpeza.setIconTextGap(50);
        btnValidacaoLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidacaoLimpezaActionPerformed(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_print.png"))); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorio.setIconTextGap(50);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValidacaoProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(btnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEepig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnValidacaoLimpeza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValidacaoLimpeza, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValidacaoProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEepig, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            if (EntradaProduto == null || EntradaProduto.isClosed()) {
                EntradaProduto = new FrmEntradaProduto();
                desktopPane.add(EntradaProduto);
                //EntradaProduto.setMaximum(true);
                Frames.centralizar(EntradaProduto);
                EntradaProduto.setVisible(true);
            } else if (EntradaProduto.isVisible() == true) {
                EntradaProduto.moveToFront();
                EntradaProduto.setSelected(true);
                EntradaProduto.show();
                desktopPane.repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir" + e);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        dispose();
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnValidacaoProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidacaoProcessosActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            if (EntradaValidacaoProcesso == null || EntradaValidacaoProcesso.isClosed()) {
                EntradaValidacaoProcesso = new FrmEntradaValidacaoProcesso();
                desktopPane.add(EntradaValidacaoProcesso);
                Frames.centralizar(EntradaValidacaoProcesso);
                EntradaValidacaoProcesso.setVisible(true);
            } else if (EntradaValidacaoProcesso.isVisible() == true) {
                EntradaValidacaoProcesso.moveToFront();
                EntradaValidacaoProcesso.setSelected(true);
                EntradaValidacaoProcesso.show();
                desktopPane.repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir" + e);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        dispose();
    }//GEN-LAST:event_btnValidacaoProcessosActionPerformed

    private void btnEepigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEepigActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            if (EntradaEEPIG == null || EntradaEEPIG.isClosed()) {
                EntradaEEPIG = new FrmEntradaEEPIG();
                desktopPane.add(EntradaEEPIG);
                Frames.centralizar(EntradaEEPIG);
                EntradaEEPIG.setVisible(true);
            } else if (EntradaEEPIG.isVisible() == true) {
                EntradaEEPIG.moveToFront();
                EntradaEEPIG.setSelected(true);
                EntradaEEPIG.show();
                desktopPane.repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir" + e);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        dispose();
    }//GEN-LAST:event_btnEepigActionPerformed

    private void btnDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucaoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            if (EntradaDevolucao == null || EntradaDevolucao.isClosed()) {
                EntradaDevolucao = new FrmEntradaDevolucao();
                desktopPane.add(EntradaDevolucao);
                Frames.centralizar(EntradaDevolucao);
                EntradaDevolucao.setVisible(true);
            } else if (EntradaDevolucao.isVisible() == true) {
                EntradaDevolucao.moveToFront();
                EntradaDevolucao.setSelected(true);
                EntradaDevolucao.show();
                desktopPane.repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir" + e);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        dispose();
    }//GEN-LAST:event_btnDevolucaoActionPerformed

    private void btnValidacaoLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidacaoLimpezaActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            if (EntradaValidacaoLimpeza == null || EntradaValidacaoLimpeza.isClosed()) {
                EntradaValidacaoLimpeza = new FrmEntradaValidacaoLimpeza();
                desktopPane.add(EntradaValidacaoLimpeza);
                Frames.centralizar(EntradaValidacaoLimpeza);
                EntradaValidacaoLimpeza.setVisible(true);
            } else if (EntradaValidacaoLimpeza.isVisible() == true) {
                EntradaValidacaoLimpeza.moveToFront();
                EntradaValidacaoLimpeza.setSelected(true);
                EntradaValidacaoLimpeza.show();
                desktopPane.repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir" + e);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        dispose();
    }//GEN-LAST:event_btnValidacaoLimpezaActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        FrmImpressaoRelatorioRecepcao frm = new FrmImpressaoRelatorioRecepcao(null, true);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMenuEntrada dialog = new FrmMenuEntrada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolucao;
    private javax.swing.JButton btnEepig;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnValidacaoLimpeza;
    private javax.swing.JButton btnValidacaoProcessos;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
