package Frm.Recepcao;

import Classes.Acesso.RegistroRfAcesso;
import Classes.DAO.HistoricoMetodologiaDAO;
import Classes.DAO.RegistroRfDAO;
import Frm.Login.FrmSalvar;
import Classes.Modelo.RegistroRf;
import Classes.Util.DataHora;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael
 */
public final class FrmRegistroRf extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoJInternalFrame
     */
    public FrmRegistroRf() {
        initComponents();
        setTitle("Registro de Referência Futura");
        setResizable(false);
        readRegistroRf();
        RegistroRfAcesso Acesso = new RegistroRfAcesso();
        Acesso.verificarAcessoRegistroRf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnExcluir = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnAtualizar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnCaixas = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnImprimir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisarMetodologia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroRf = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        cmbLimitPesquisar = new javax.swing.JComboBox<String>();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);
        jToolBar1.add(jSeparator6);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);
        jToolBar1.add(jSeparator1);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_close.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setPreferredSize(new java.awt.Dimension(60, 60));
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluir);
        jToolBar1.add(jSeparator8);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setFocusable(false);
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAtualizar);
        jToolBar1.add(jSeparator5);

        btnCaixas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_estoque.png"))); // NOI18N
        btnCaixas.setText("Caixas");
        btnCaixas.setFocusable(false);
        btnCaixas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaixas.setPreferredSize(new java.awt.Dimension(60, 60));
        btnCaixas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCaixas);
        jToolBar1.add(jSeparator7);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimir);

        jLabel4.setText("Pesquisar:");

        txtPesquisarMetodologia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarMetodologiaKeyReleased(evt);
            }
        });

        tblRegistroRf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "caixa_id", "material_id", "Lote", "Caixa", "Material", "Produto", "Centro de Custo", "Depósito", "Quantidade (g)", "Data Registro", "Resposável"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegistroRf.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblRegistroRf.getTableHeader().setReorderingAllowed(false);
        tblRegistroRf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistroRfMouseClicked(evt);
            }
        });
        tblRegistroRf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblRegistroRfKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistroRf);
        if (tblRegistroRf.getColumnModel().getColumnCount() > 0) {
            tblRegistroRf.getColumnModel().getColumn(0).setMinWidth(0);
            tblRegistroRf.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblRegistroRf.getColumnModel().getColumn(0).setMaxWidth(0);
            tblRegistroRf.getColumnModel().getColumn(1).setMinWidth(0);
            tblRegistroRf.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblRegistroRf.getColumnModel().getColumn(1).setMaxWidth(0);
            tblRegistroRf.getColumnModel().getColumn(2).setMinWidth(0);
            tblRegistroRf.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblRegistroRf.getColumnModel().getColumn(2).setMaxWidth(0);
            tblRegistroRf.getColumnModel().getColumn(3).setMinWidth(150);
            tblRegistroRf.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblRegistroRf.getColumnModel().getColumn(3).setMaxWidth(150);
            tblRegistroRf.getColumnModel().getColumn(4).setMinWidth(120);
            tblRegistroRf.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblRegistroRf.getColumnModel().getColumn(4).setMaxWidth(120);
            tblRegistroRf.getColumnModel().getColumn(5).setMinWidth(80);
            tblRegistroRf.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblRegistroRf.getColumnModel().getColumn(5).setMaxWidth(80);
            tblRegistroRf.getColumnModel().getColumn(6).setMinWidth(500);
            tblRegistroRf.getColumnModel().getColumn(6).setPreferredWidth(500);
            tblRegistroRf.getColumnModel().getColumn(6).setMaxWidth(500);
            tblRegistroRf.getColumnModel().getColumn(7).setMinWidth(120);
            tblRegistroRf.getColumnModel().getColumn(7).setPreferredWidth(120);
            tblRegistroRf.getColumnModel().getColumn(7).setMaxWidth(120);
            tblRegistroRf.getColumnModel().getColumn(8).setMinWidth(120);
            tblRegistroRf.getColumnModel().getColumn(8).setPreferredWidth(120);
            tblRegistroRf.getColumnModel().getColumn(8).setMaxWidth(120);
            tblRegistroRf.getColumnModel().getColumn(9).setMinWidth(120);
            tblRegistroRf.getColumnModel().getColumn(9).setPreferredWidth(120);
            tblRegistroRf.getColumnModel().getColumn(9).setMaxWidth(120);
            tblRegistroRf.getColumnModel().getColumn(10).setMinWidth(150);
            tblRegistroRf.getColumnModel().getColumn(10).setPreferredWidth(150);
            tblRegistroRf.getColumnModel().getColumn(10).setMaxWidth(150);
            tblRegistroRf.getColumnModel().getColumn(11).setMinWidth(120);
            tblRegistroRf.getColumnModel().getColumn(11).setPreferredWidth(120);
            tblRegistroRf.getColumnModel().getColumn(11).setMaxWidth(120);
        }

        jLabel11.setText("Visualizar:");

        cmbLimitPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100", "1000", "10000", "100000", "1000000" }));
        cmbLimitPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLimitPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarMetodologia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbLimitPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbLimitPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesquisarMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblRegistroRf.getSelectedRow() != -1) {
            FrmRegistroRfCadastro frm = new FrmRegistroRfCadastro(null, true,
                    (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 0),
                    (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 1),
                    (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 2));
            frm.setVisible(true);
            readRegistroRf();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        RegistroRf regrf = new RegistroRf();
        RegistroRfDAO regrfDao = new RegistroRfDAO();
        FrmRegistroRfProcurarCaixa frm = new FrmRegistroRfProcurarCaixa(null, true, regrf);
        frm.setVisible(true);
        if (regrf.getCaixa_rf_id() > 0) {
            Thread t1 = new Thread() {
                @Override
                public void run() {
                    regrfDao.printLotesCaixa(System.getProperty("user"), regrf.getCaixa_rf_id());
                }
            };
            t1.start();
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtPesquisarMetodologiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarMetodologiaKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblRegistroRf.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblRegistroRf.setRowSorter(sorter);
        String text = txtPesquisarMetodologia.getText().trim();
        String parametro = "*";
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text.toUpperCase()));
        }
    }//GEN-LAST:event_txtPesquisarMetodologiaKeyReleased

    private void tblRegistroRfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistroRfMouseClicked
        if (evt.getClickCount() == 2) {
            FrmRegistroRfCadastro frm = new FrmRegistroRfCadastro(null, true,
                    (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 0),
                    (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 1),
                    (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 2));
            frm.setVisible(true);
            readRegistroRf();
        }
    }//GEN-LAST:event_tblRegistroRfMouseClicked

    private void tblRegistroRfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRegistroRfKeyReleased
        if (tblRegistroRf.getSelectedRow() != -1) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                FrmRegistroRfCadastro frm = new FrmRegistroRfCadastro(null, true,
                        (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 0),
                        (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 1),
                        (Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 2));
                frm.setVisible(true);
                readRegistroRf();
            }
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                deletarRegistroRf((Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 0));
                readRegistroRf();
            }
        }
    }//GEN-LAST:event_tblRegistroRfKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        FrmRegistroRfCadastro frm = new FrmRegistroRfCadastro(null, true);
        frm.setVisible(true);
        readRegistroRf();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblRegistroRf.getSelectedRow() != -1) {
            deletarRegistroRf((Integer) tblRegistroRf.getValueAt(tblRegistroRf.getSelectedRow(), 0));
            readRegistroRf();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        readRegistroRf();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void cmbLimitPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLimitPesquisarActionPerformed
        readRegistroRf();
    }//GEN-LAST:event_cmbLimitPesquisarActionPerformed

    private void btnCaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixasActionPerformed
        FrmRegistroRfCaixa frm = new FrmRegistroRfCaixa(null, true);
        frm.setVisible(true);
        readRegistroRf();
    }//GEN-LAST:event_btnCaixasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    public static javax.swing.JButton btnCaixas;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnExcluir;
    public static javax.swing.JButton btnImprimir;
    public static javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cmbLimitPesquisar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblRegistroRf;
    private javax.swing.JTextField txtPesquisarMetodologia;
    // End of variables declaration//GEN-END:variables

    private void readRegistroRf() {
        DefaultTableModel model = (DefaultTableModel) tblRegistroRf.getModel();
        RegistroRfDAO regrfDAO = new RegistroRfDAO();
        model.setNumRows(0);
        for (RegistroRf regrf : regrfDAO.readRegistroRf(Integer.valueOf(cmbLimitPesquisar.getSelectedItem().toString()))) {
            model.addRow(new Object[]{
                regrf.getRegistro_rf_id(),
                regrf.getCaixa_rf_id(),
                regrf.getMaterial().getMaterial_id(),
                regrf.getLote(),
                regrf.getCaixa(),
                regrf.getMaterial().getCod_material(),
                regrf.getMaterial().getNome_material(),
                regrf.getCentro_custo(),
                regrf.getDeposito(),
                regrf.getQuantidade(),
                DataHora.getStringDateTime(regrf.getData_registro()),
                regrf.getUser_registro().getUser()
            });
        }
    }

    private void deletarRegistroRf(Integer id) {
        RegistroRfAcesso Acesso = new RegistroRfAcesso();
        if (Acesso.verificarDeletarDadosRegistroRf()) {
            RegistroRf regrf = new RegistroRf();
            RegistroRfDAO regrfDAO = new RegistroRfDAO();
            regrf.setRegistro_rf_id(id);
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            FrmSalvar frmSalvar = new FrmSalvar(null, true);
            frmSalvar.setVisible(true);
            if (FrmSalvar.senha()) {
                regrfDAO.deleteRegistroRf(regrf);
            }
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }

}
