/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Laboratorio;

import Classes.DAO.TrocaTurnoConferenciaDAO;
import Classes.Modelo.TrocaTurnoConferencia;
import Classes.Util.DataHora;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public class FrmAtaConferencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmLogBooK
     */
    public FrmAtaConferencia() {
        initComponents();
        setTitle("Troca de Turno Conferência");
        readAtaConferencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEquipamentos = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPassagemTurno = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        btnAtualizarEquipamento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisarTrocaTurno = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTrocaTurno = new javax.swing.JTable();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnPassagemTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_edit.png"))); // NOI18N
        btnPassagemTurno.setText("Novo");
        btnPassagemTurno.setToolTipText("Atualizar");
        btnPassagemTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassagemTurnoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPassagemTurno);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btnAtualizarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_raio.png"))); // NOI18N
        btnAtualizarEquipamento.setText("Atualizar");
        btnAtualizarEquipamento.setToolTipText("Atualizar");
        btnAtualizarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarEquipamentoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAtualizarEquipamento);

        jLabel4.setText("Pesquisar:");

        txtPesquisarTrocaTurno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarTrocaTurnoKeyReleased(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Trocas de Turno"));

        tblTrocaTurno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Turno", "Descrição", "Data", "Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTrocaTurno.setSurrendersFocusOnKeystroke(true);
        tblTrocaTurno.getTableHeader().setReorderingAllowed(false);
        tblTrocaTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrocaTurnoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblTrocaTurno);
        if (tblTrocaTurno.getColumnModel().getColumnCount() > 0) {
            tblTrocaTurno.getColumnModel().getColumn(0).setMinWidth(0);
            tblTrocaTurno.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblTrocaTurno.getColumnModel().getColumn(0).setMaxWidth(0);
            tblTrocaTurno.getColumnModel().getColumn(1).setMinWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(1).setMaxWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(3).setMinWidth(150);
            tblTrocaTurno.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblTrocaTurno.getColumnModel().getColumn(3).setMaxWidth(150);
            tblTrocaTurno.getColumnModel().getColumn(4).setMinWidth(120);
            tblTrocaTurno.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblTrocaTurno.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlEquipamentosLayout = new javax.swing.GroupLayout(pnlEquipamentos);
        pnlEquipamentos.setLayout(pnlEquipamentosLayout);
        pnlEquipamentosLayout.setHorizontalGroup(
            pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarTrocaTurno))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlEquipamentosLayout.setVerticalGroup(
            pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                .addGroup(pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarTrocaTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlEquipamentos);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarEquipamentoActionPerformed
        readAtaConferencia();
    }//GEN-LAST:event_btnAtualizarEquipamentoActionPerformed

    private void btnPassagemTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassagemTurnoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FrmTrocaTurnoConferencia frm = new FrmTrocaTurnoConferencia(null, true);
        frm.setVisible(true);
        readAtaConferencia();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPassagemTurnoActionPerformed

    private void txtPesquisarTrocaTurnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarTrocaTurnoKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblTrocaTurno.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblTrocaTurno.setRowSorter(sorter);
        String text = txtPesquisarTrocaTurno.getText().trim().toUpperCase();
        String parametro = "*";
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text.toUpperCase()));
        }
    }//GEN-LAST:event_txtPesquisarTrocaTurnoKeyReleased

    private void tblTrocaTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrocaTurnoMouseClicked
        if (evt.getClickCount() == 2) {
            boolean salvar = false;
            if (tblTrocaTurno.getSelectedRow() == 0) {
                salvar = true;
            }
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            FrmTrocaTurnoConferencia frm = new FrmTrocaTurnoConferencia(null, true,
                    (Integer) tblTrocaTurno.getValueAt(tblTrocaTurno.getSelectedRow(), 0),
                    tblTrocaTurno.getValueAt(tblTrocaTurno.getSelectedRow(), 4).toString(),
                    false, salvar);
            frm.setVisible(true);
            readAtaConferencia();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_tblTrocaTurnoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarEquipamento;
    public static javax.swing.JButton btnPassagemTurno;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel pnlEquipamentos;
    private javax.swing.JTable tblTrocaTurno;
    private javax.swing.JTextField txtPesquisarTrocaTurno;
    // End of variables declaration//GEN-END:variables

    private void readAtaConferencia() {
        try {
            TrocaTurnoConferenciaDAO turnoDAO = new TrocaTurnoConferenciaDAO();
            DefaultTableModel model = (DefaultTableModel) tblTrocaTurno.getModel();
            model.setNumRows(0);
            for (TrocaTurnoConferencia turno : turnoDAO.readTrocaTurnoConferencia()) {
                model.addRow(new Object[]{
                    turno.getTroca_turno_conferencia_id(),
                    turno.getTurno(),
                    turno.getDescricao_turno(),
                    DataHora.getStringDateTime(turno.getData_registro()),
                    turno.getUser_name().getUser()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        }
    }

}
