/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm.Laboratorio;

import Classes.Acesso.DissolutorAcesso;
import Classes.DAO.DissolutorDAO;
import Classes.DAO.SetorDAO;
import Frm.Login.FrmSalvar;
import Classes.Modelo.Dissolutor;
import Classes.Modelo.Setor;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael
 */
public class FrmDissolutor extends javax.swing.JInternalFrame {

    private boolean novoEquipamento = false;
    private TreeMap<Integer, String> categoryMap = new TreeMap<Integer, String>();

    private int getKeyForValue(String value) {
        for (Map.Entry<Integer, String> entry : categoryMap.entrySet()) {
            if (entry.getValue().equals(value)) {
                return entry.getKey();
            }
        }
        return 0;
    }

    /**
     * Creates new form NovoJInternalFrame
     */
    public FrmDissolutor() {
        initComponents();
        setTitle("Dissolutores");
        readDissolutores();
        tblPaneEquipamentos.setEnabledAt(1, false);
        txtHastes.setModel(new SpinnerNumberModel(0, 0, 24, 1));
        DissolutorAcesso Acesso = new DissolutorAcesso();
        Acesso.verificarAcesso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPaneEquipamentos = new javax.swing.JTabbedPane();
        pnlUsuarios = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDissolutores = new javax.swing.JTable();
        txtPesquisarEquipamentos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnEditar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnExcluir = new javax.swing.JButton();
        pnlDados = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtDissolutorName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbSetor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHastes = new javax.swing.JSpinner();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtTermometro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRotor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTimer_1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTimer_2 = new javax.swing.JTextField();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dissolutores"));

        tblDissolutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tag", "n° Hastes", "Tipo", "Setor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDissolutores.setSurrendersFocusOnKeystroke(true);
        tblDissolutores.getTableHeader().setReorderingAllowed(false);
        tblDissolutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDissolutoresMouseClicked(evt);
            }
        });
        tblDissolutores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDissolutoresKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDissolutores);
        if (tblDissolutores.getColumnModel().getColumnCount() > 0) {
            tblDissolutores.getColumnModel().getColumn(0).setMinWidth(0);
            tblDissolutores.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblDissolutores.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDissolutores.getColumnModel().getColumn(2).setMinWidth(100);
            tblDissolutores.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblDissolutores.getColumnModel().getColumn(2).setMaxWidth(100);
            tblDissolutores.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        txtPesquisarEquipamentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarEquipamentosKeyReleased(evt);
            }
        });

        jLabel4.setText("Pesquisar:");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);
        jToolBar1.add(jSeparator1);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);
        jToolBar1.add(jSeparator2);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_close.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluir);

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarEquipamentos))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblPaneEquipamentos.addTab("Dissolutores", pnlUsuarios);

        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamento"));

        jLabel1.setText("Tag:");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Tipo:");

        jLabel22.setText("Setor:");

        jLabel5.setText("Marca:");

        jLabel6.setText("Hates:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHastes)
                    .addComponent(txtTipo)
                    .addComponent(txtDissolutorName, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addComponent(txtMarca)
                    .addComponent(cmbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDissolutorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtHastes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tag's"));

        jLabel11.setText("Rotor:");

        jLabel12.setText("Timer 1:");

        jLabel16.setText("Termometro:");

        jLabel13.setText("Timer 2:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTermometro, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtRotor)
                    .addComponent(txtTimer_1)
                    .addComponent(txtTimer_2))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTermometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimer_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimer_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        tblPaneEquipamentos.addTab("Dados", pnlDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPaneEquipamentos, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPaneEquipamentos, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDissolutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDissolutoresMouseClicked
        if (evt.getClickCount() == 2) {
            carregarDados((Integer) tblDissolutores.getValueAt(tblDissolutores.getSelectedRow(), 0));
            novoEquipamento = false;
        }
    }//GEN-LAST:event_tblDissolutoresMouseClicked

    private void txtPesquisarEquipamentosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarEquipamentosKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblDissolutores.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblDissolutores.setRowSorter(sorter);
        String text = txtPesquisarEquipamentos.getText().trim();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_txtPesquisarEquipamentosKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (txtDissolutorName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tag inválida");
            txtDissolutorName.requestFocus();
        } else if (txtModelo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Modelo inválido");
            txtModelo.requestFocus();
        } else if (txtTipo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tipo inválido");
            txtTipo.requestFocus();
        } else if (txtMarca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Marca inválida");
            txtMarca.requestFocus();
        } else if (cmbSetor.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Setor inválido");
            txtMarca.requestFocus();
        } else if (txtTermometro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Termometro inválido");
            txtTermometro.requestFocus();
        } else if (txtRotor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Rotor inválido");
            txtRotor.requestFocus();
        } else if (txtTimer_1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Timer_1 inválido");
            txtTimer_1.requestFocus();
        } else if (novoEquipamento) {
            FrmSalvar frmSalvar = new FrmSalvar(null, true);
            frmSalvar.setVisible(true);
            if (FrmSalvar.senha()) {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                criarDissolutor();
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        } else {
            FrmSalvar frmSalvar = new FrmSalvar(null, true);
            frmSalvar.setVisible(true);
            if (FrmSalvar.senha()) {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                atulizarEquipamento((Integer) tblDissolutores.getValueAt(tblDissolutores.getSelectedRow(), 0));
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fecharDados();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblDissolutoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDissolutoresKeyReleased
        if (tblDissolutores.getSelectedRow() != -1) {
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                deletarDados((Integer) tblDissolutores.getValueAt(tblDissolutores.getSelectedRow(), 0));
            }
        }
    }//GEN-LAST:event_tblDissolutoresKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblDissolutores.getSelectedRow() != -1) {
            carregarDados((Integer) tblDissolutores.getValueAt(tblDissolutores.getSelectedRow(), 0));
            novoEquipamento = false;
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        abrirDados();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblDissolutores.getSelectedRow() != -1) {
            deletarDados((Integer) tblDissolutores.getValueAt(tblDissolutores.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnExcluir;
    public static javax.swing.JButton btnNovo;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbSetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JTable tblDissolutores;
    private javax.swing.JTabbedPane tblPaneEquipamentos;
    private javax.swing.JTextField txtDissolutorName;
    private javax.swing.JSpinner txtHastes;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPesquisarEquipamentos;
    private javax.swing.JTextField txtRotor;
    private javax.swing.JTextField txtTermometro;
    private javax.swing.JTextField txtTimer_1;
    private javax.swing.JTextField txtTimer_2;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

    public final void readDissolutores() {
        DefaultTableModel model = (DefaultTableModel) tblDissolutores.getModel();
        DissolutorDAO dissDao = new DissolutorDAO();
        model.setNumRows(0);
        for (Dissolutor diss : dissDao.readDissolutor()) {
            model.addRow(new Object[]{
                diss.getDissolutor_id(),
                diss.getDissolutor_name(),
                diss.getHastes(),
                diss.getTipo(),
                diss.getSetor().getSigla_setor()
            });
        }
    }

    public final void readSetor() {
        cmbSetor.removeAllItems();
        cmbSetor.addItem("");
        categoryMap.clear();
        SetorDAO setorDao = new SetorDAO();
        for (Setor setor : setorDao.readSetor()) {
            Integer id = setor.getSetor_id();
            String name = setor.getSigla_setor();
            cmbSetor.addItem(name);
            categoryMap.put(id, name);
        }
    }

    private void limparCampos() {
        txtDissolutorName.setText(null);
        txtModelo.setText(null);
        txtMarca.setText(null);
        txtDissolutorName.setText(null);
        txtModelo.setText(null);
        txtTipo.setText(null);
        txtTermometro.setText(null);
        txtRotor.setText(null);
        txtTimer_1.setText(null);
    }

    private void criarDissolutor() {
        Dissolutor diss = new Dissolutor();
        DissolutorDAO dissDAO = new DissolutorDAO();
        try {
            diss.setDissolutor_name(txtDissolutorName.getText().toUpperCase().trim());
            diss.setModelo(txtModelo.getText().toUpperCase().trim());
            diss.setTipo(txtTipo.getText().toUpperCase().trim());
            diss.setMarca(txtMarca.getText().toUpperCase().trim());
            Setor setor = new Setor();
            setor.setSetor_id(getKeyForValue(cmbSetor.getSelectedItem().toString()));
            diss.setSetor(setor);
            diss.setHastes((Integer) txtHastes.getValue());
            diss.setTermometro(txtTermometro.getText().toUpperCase().trim());
            diss.setTimer_1(txtTimer_1.getText().toUpperCase().trim());
            diss.setTimer_2(txtTimer_2.getText().toUpperCase().trim());
            diss.setRotor(txtRotor.getText().toUpperCase().trim());
            dissDAO.createDissolutor(diss);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        } finally {
            fecharDados();
        }
    }

    private void fecharDados() {
        tblPaneEquipamentos.setEnabledAt(0, true);
        tblPaneEquipamentos.setEnabledAt(1, false);
        tblPaneEquipamentos.setSelectedIndex(0);
        txtPesquisarEquipamentos.setText(null);
        tblDissolutores.setRowSorter(null);
        DissolutorAcesso Acesso = new DissolutorAcesso();
        Acesso.verificarAcesso();
        limparCampos();
        readDissolutores();
    }

    private void abrirDados() {
        DissolutorAcesso Acesso = new DissolutorAcesso();
        if (Acesso.verificarAbrirDados()) {
            tblPaneEquipamentos.setEnabledAt(0, false);
            tblPaneEquipamentos.setEnabledAt(1, true);
            tblPaneEquipamentos.setSelectedIndex(1);
            limparCampos();
            novoEquipamento = true;
            readSetor();
        }
    }

    private void carregarDados(Integer id) {
        DissolutorAcesso Acesso = new DissolutorAcesso();
        if (Acesso.verificarCarregarDados()) {
            readSetor();
            Dissolutor diss = new Dissolutor();
            diss.setDissolutor_id(id);
            DissolutorDAO dissDAO = new DissolutorDAO();
            dissDAO.selectDissolutor(diss);
            txtDissolutorName.setText(diss.getDissolutor_name());
            txtModelo.setText(diss.getModelo());
            txtTipo.setText(diss.getTipo());
            txtMarca.setText(diss.getMarca());
            String[] setor = {diss.getSetor().getSigla_setor()};
            cmbSetor.setSelectedItem(setor[0]);
            txtHastes.setValue(diss.getHastes());
            txtTermometro.setText(diss.getTermometro());
            txtTimer_1.setText(diss.getTimer_1());
            txtTimer_2.setText(diss.getTimer_2());
            txtRotor.setText(diss.getRotor());
            tblPaneEquipamentos.setEnabledAt(0, false);
            tblPaneEquipamentos.setEnabledAt(1, true);
            tblPaneEquipamentos.setSelectedIndex(1);
        }
    }

    private void atulizarEquipamento(Integer id) {
        Dissolutor diss = new Dissolutor();
        DissolutorDAO dissDAO = new DissolutorDAO();
        try {
            diss.setDissolutor_id(id);
            diss.setDissolutor_name(txtDissolutorName.getText().toUpperCase().trim());
            diss.setModelo(txtModelo.getText().toUpperCase().trim());
            diss.setTipo(txtTipo.getText().toUpperCase().trim());
            diss.setMarca(txtMarca.getText().toUpperCase().trim());
            Setor setor = new Setor();
            setor.setSetor_id(getKeyForValue(cmbSetor.getSelectedItem().toString()));
            diss.setSetor(setor);
            diss.setHastes((Integer) txtHastes.getValue());
            diss.setTermometro(txtTermometro.getText().toUpperCase().trim());
            diss.setTimer_1(txtTimer_1.getText().toUpperCase().trim());
            diss.setTimer_2(txtTimer_2.getText().toUpperCase().trim());
            diss.setRotor(txtRotor.getText().toUpperCase().trim());
            dissDAO.updateDissolutor(diss);
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar dados: " + e);
        } finally {
            fecharDados();
        }
    }

    private void deletarDados(Integer id) {
        DissolutorAcesso Acesso = new DissolutorAcesso();
        if (Acesso.verificarDeletarDados()) {
            Dissolutor diss = new Dissolutor();
            DissolutorDAO dissDAO = new DissolutorDAO();
            try {
                int dialogResult = JOptionPane.showConfirmDialog(null,
                        "Realmente Deseja Excluir esse Equipamento?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (dialogResult == 0) {
                    diss.setDissolutor_id(id);
                    dissDAO.deleteDissolutor(diss);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao atulalizar dados: " + e);
            } finally {
                fecharDados();
            }
        }
    }

}
