/*
 * Copyright (C) 2018 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Programacao;

import Classes.DAO.CromatografoDAO;
import Classes.DAO.EquipesDAO;
import Frm.Config.FrmSelecionaUsuario;
import Frm.Login.FrmSalvar;
import Classes.Modelo.Cromatografo;
import Classes.Modelo.Equipes;
import Classes.Modelo.Usuario;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael.lopes
 */
public class FrmCadastroEquipes extends javax.swing.JDialog {

    private Integer equipe_id;

    /**
     * Creates new form FrmCadastroEquipes
     */
    public FrmCadastroEquipes(java.awt.Frame parent, boolean modal, Integer id) {
        super(parent, modal);
        initComponents();
        readTurno();
        readEquipamento();
        readEquipe();
        equipe_id = id;
        if (id > 0) {
            carregarDados(id);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        cmbEquipamento = new javax.swing.JComboBox();
        Equipe = new javax.swing.JLabel();
        cmbEquipe = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        cmbSetorCampanhas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnAdicionarMetodo1 = new javax.swing.JButton();
        btnRemoverMetodo1 = new javax.swing.JButton();
        btnSalvarEquipe = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel9.setText("Turno:");

        cmbTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel25.setText("Equipamento:");

        Equipe.setText("Equipe:");

        jLabel27.setText("Setor:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Membros da Equipe"));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuário", "Nome Completo", "Função"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.setSurrendersFocusOnKeystroke(true);
        tblUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
            tblUsuarios.getColumnModel().getColumn(1).setMinWidth(120);
            tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblUsuarios.getColumnModel().getColumn(1).setMaxWidth(120);
            tblUsuarios.getColumnModel().getColumn(3).setMinWidth(200);
            tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblUsuarios.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        btnAdicionarMetodo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdicionarMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMetodo1ActionPerformed(evt);
            }
        });

        btnRemoverMetodo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnRemoverMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMetodo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Equipe, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEquipe, 0, 225, Short.MAX_VALUE)
                            .addComponent(cmbTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEquipamento, 0, 225, Short.MAX_VALUE)
                            .addComponent(cmbSetorCampanhas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarMetodo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverMetodo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Equipe)
                    .addComponent(cmbEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(cmbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel27)
                    .addComponent(cmbSetorCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAdicionarMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverMetodo1)
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSalvarEquipe.setText("Salvar");
        btnSalvarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEquipeActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarEquipe)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEquipeActionPerformed
        if (cmbEquipe.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Selecionar o nome da Equipe");
            cmbEquipe.requestFocus();
        } else if (cmbEquipamento.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Selecionar o Equipamento");
            cmbEquipamento.requestFocus();
        } else if (cmbTurno.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o Turno");
            cmbTurno.requestFocus();
        } else if (equipe_id > 0) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            FrmSalvar frmSalvar = new FrmSalvar(null, true);
            frmSalvar.setVisible(true);
            if (FrmSalvar.senha()) {
                atulizarEquipe(equipe_id);
            }
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        } else {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            FrmSalvar frmSalvar = new FrmSalvar(null, true);
            frmSalvar.setVisible(true);
            if (FrmSalvar.senha()) {
                criarEquipe();
            }
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_btnSalvarEquipeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMetodo1ActionPerformed
//        novoMetodologia = 1;
//        carregarMetodo();
    }//GEN-LAST:event_btnAdicionarMetodo1ActionPerformed

    private void btnRemoverMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMetodo1ActionPerformed
//        txtCodMetodo1.setText("");
//        txtMetodo1.setText("");
    }//GEN-LAST:event_btnRemoverMetodo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCadastroEquipes dialog = new FrmCadastroEquipes(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Equipe;
    private javax.swing.JButton btnAdicionarMetodo1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemoverMetodo1;
    public static javax.swing.JButton btnSalvarEquipe;
    private javax.swing.JComboBox cmbEquipamento;
    private javax.swing.JComboBox cmbEquipe;
    private javax.swing.JComboBox cmbSetorCampanhas;
    private javax.swing.JComboBox cmbTurno;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables

    public final void readTurno() {
        cmbTurno.removeAllItems();
        cmbTurno.addItem("1T");
        cmbTurno.addItem("2T");
        cmbTurno.addItem("3T");
        cmbTurno.addItem("Comercial");
    }

    public final void readEquipamento() {
        cmbEquipamento.removeAllItems();
        cmbEquipamento.addItem("");
        CromatografoDAO equipDao = new CromatografoDAO();
        for (Cromatografo equip : equipDao.readCromatografo()) {
            cmbEquipamento.addItem(equip.getSystem_name());
        }
    }

    public final void readEquipe() {
        cmbEquipe.removeAllItems();
        cmbEquipe.addItem("");
        cmbEquipe.addItem("Celula1");
        cmbEquipe.addItem("Celula2");
        cmbEquipe.addItem("Celula3");
        cmbEquipe.addItem("Celula4");
        cmbEquipe.addItem("Celula5");
        cmbEquipe.addItem("Celula6");
        cmbEquipe.addItem("Celula7");
        cmbEquipe.addItem("Celula8");
        cmbEquipe.addItem("Celula9");
    }

    private void criarEquipe() {
        try {
            Equipes equipe = new Equipes();
            EquipesDAO equipeDAO = new EquipesDAO();
            Cromatografo equip = new Cromatografo();
            equipe.setNome_equipe(cmbEquipe.getSelectedItem().toString());
            equip.setSystem_name(cmbEquipamento.getSelectedItem().toString());
            equipe.setCromatografo(equip);
            equipe.setTurno(cmbEquipamento.getSelectedItem().toString());
            
            
            
            equipe.setNome_equipe(cmbEquipe.getSelectedItem().toString());
            equipe.setNome_equipe(cmbEquipe.getSelectedItem().toString());
            equipe.setNome_equipe(cmbEquipe.getSelectedItem().toString());

            //equipe.setLog_campanha_id();

            equipeDAO.createEquipes(equipe);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        }
    }

    private void atulizarEquipe(Integer id) {

    }

    public final void carregarDados(Integer campanha_id) {
//        Campanha camp = new Campanha();
//        CampanhaDAO campDAO = new CampanhaDAO();
//        camp.setLog_campanha_id(campanha_id);
//        campDAO.selectCampanhaById(camp);
//        txtNomeCampanha.setText(camp.getNome_campanha());
//        txtObs.setText(camp.getObs_campanha());
//        String[] setores = {camp.getSetor().getSigla_setor()};
//        cmbSetorCampanhas.setSelectedItem(setores[0]);
//        String[] equipamento = {camp.getCromatografo().getSystem_name()};
//        cmbEquipamento.setSelectedItem(equipamento[0]);
//        String[] analise = {camp.getAnalise().getAnalise()};
//        cmbAnalise.setSelectedItem(analise[0]);
//        String[] cor = {camp.getCor()};
//        cmbCor.setSelectedItem(cor[0]);
//        Calendar cal = Calendar.getInstance();
//        cal.setTime(camp.getPrevisao());
//        txtDataPrevisao.setDate(camp.getPrevisao());
//        txtHora.setValue((Integer) cal.get(Calendar.HOUR_OF_DAY));
//        txtMinuto.setValue((Integer) cal.get(Calendar.MINUTE));
//        String text = camp.getMetodos();
//        String a = "a";
//        String b = "b";
//        String c = "c";
//        String d = "d";
//        MetodologiaDAO mtdDAO = new MetodologiaDAO();
//        txtCodMetodo1.setText(text.substring(text.indexOf(a) + 1, text.indexOf(b)));
//        txtMetodo1.setText(mtdDAO.selectMetodologiaById(text.substring(text.indexOf(a) + 1, text.indexOf(b))));
//        txtCodMetodo2.setText(text.substring(text.indexOf(b) + 1, text.indexOf(c)));
//        txtMetodo2.setText(mtdDAO.selectMetodologiaById(text.substring(text.indexOf(b) + 1, text.indexOf(c))));
//        txtCodMetodo3.setText(text.substring(text.indexOf(c) + 1, text.indexOf(d)));
//        txtMetodo3.setText(mtdDAO.selectMetodologiaById(text.substring(text.indexOf(c) + 1, text.indexOf(d))));
//        txtCodMetodo4.setText(text.substring(text.indexOf(d) + 1, text.length()));
//        txtMetodo4.setText(mtdDAO.selectMetodologiaById(text.substring(text.indexOf(d) + 1, text.length())));
//        if (editar_campanha) {
//            cmbEquipamento.setEnabled(false);
//        } else {
//            cmbEquipamento.setEnabled(true);
//        }

    }

}
