/*
 * Copyright (C) 2018 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package Frm.Programacao;

import Classes.DAO.AtividadePreparoDAO;
import Classes.Modelo.AtividadePreparo;
import Classes.Util.DataHora;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public class FrmLotesPreparo extends javax.swing.JDialog {

    /**
     * Creates new form FrmLotesEquipamento
     */
    public FrmLotesPreparo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Lotes - Preparo");
        readPreparo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLotesPreparo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisarPreparo = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPreparo = new javax.swing.JTable();
        btnAtualizarPreparo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setText("Pesquisar:");

        txtPesquisarPreparo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarPreparoKeyReleased(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Lotes"));

        tblPreparo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Metodo", "Lote", "Equipamento", "Status", "Data Registro", "Analista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPreparo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblPreparo);
        if (tblPreparo.getColumnModel().getColumnCount() > 0) {
            tblPreparo.getColumnModel().getColumn(0).setMinWidth(0);
            tblPreparo.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblPreparo.getColumnModel().getColumn(0).setMaxWidth(0);
            tblPreparo.getColumnModel().getColumn(1).setMinWidth(300);
            tblPreparo.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblPreparo.getColumnModel().getColumn(1).setMaxWidth(300);
            tblPreparo.getColumnModel().getColumn(2).setMinWidth(500);
            tblPreparo.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblPreparo.getColumnModel().getColumn(2).setMaxWidth(500);
            tblPreparo.getColumnModel().getColumn(3).setMinWidth(100);
            tblPreparo.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblPreparo.getColumnModel().getColumn(3).setMaxWidth(100);
            tblPreparo.getColumnModel().getColumn(4).setMinWidth(120);
            tblPreparo.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblPreparo.getColumnModel().getColumn(4).setMaxWidth(120);
            tblPreparo.getColumnModel().getColumn(5).setMinWidth(100);
            tblPreparo.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblPreparo.getColumnModel().getColumn(5).setMaxWidth(100);
            tblPreparo.getColumnModel().getColumn(6).setMinWidth(150);
            tblPreparo.getColumnModel().getColumn(6).setPreferredWidth(150);
            tblPreparo.getColumnModel().getColumn(6).setMaxWidth(150);
            tblPreparo.getColumnModel().getColumn(7).setMinWidth(120);
            tblPreparo.getColumnModel().getColumn(7).setPreferredWidth(120);
            tblPreparo.getColumnModel().getColumn(7).setMaxWidth(120);
        }

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        );

        btnAtualizarPreparo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_raio.png"))); // NOI18N
        btnAtualizarPreparo.setText("Atualizar");
        btnAtualizarPreparo.setToolTipText("Atualizar");
        btnAtualizarPreparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarPreparoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLotesPreparoLayout = new javax.swing.GroupLayout(pnlLotesPreparo);
        pnlLotesPreparo.setLayout(pnlLotesPreparoLayout);
        pnlLotesPreparoLayout.setHorizontalGroup(
            pnlLotesPreparoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLotesPreparoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLotesPreparoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLotesPreparoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarPreparo))
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLotesPreparoLayout.createSequentialGroup()
                        .addGap(0, 894, Short.MAX_VALUE)
                        .addComponent(btnAtualizarPreparo)))
                .addContainerGap())
        );
        pnlLotesPreparoLayout.setVerticalGroup(
            pnlLotesPreparoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLotesPreparoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLotesPreparoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarPreparo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLotesPreparo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLotesPreparo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarPreparoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarPreparoKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblPreparo.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblPreparo.setRowSorter(sorter);
        String text = txtPesquisarPreparo.getText().trim().toUpperCase();
        String parametro = "*";
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_txtPesquisarPreparoKeyReleased

    private void btnAtualizarPreparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarPreparoActionPerformed
        readPreparo();
    }//GEN-LAST:event_btnAtualizarPreparoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLotesPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLotesPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLotesPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLotesPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLotesPreparo dialog = new FrmLotesPreparo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarPreparo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlLotesPreparo;
    private javax.swing.JTable tblPreparo;
    private javax.swing.JTextField txtPesquisarPreparo;
    // End of variables declaration//GEN-END:variables


    private void readPreparo() {
        DefaultTableModel model = (DefaultTableModel) tblPreparo.getModel();
        AtividadePreparoDAO atvprepDao = new AtividadePreparoDAO();
        model.setNumRows(0);
        for (AtividadePreparo atvprep : atvprepDao.readPreparo()) {
            model.addRow(new Object[]{
                atvprep.getAtividade_preparo_id(),
                (atvprep.getAnalise().getAnalise() == null ? "" : atvprep.getAnalise().getAnalise() + "   ")
                + (atvprep.getTipo_preparo() == null ? "" : atvprep.getTipo_preparo() + " - ")
                + (atvprep.getDescricao_preparo() == null ? "" : atvprep.getDescricao_preparo()),
                ((atvprep.getMetodologia().getMetodo_id() == 0) ? "MULTIPROPÓSITO"
                : atvprep.getMetodologia().getCod_metodo() + " - "
                + (atvprep.getMetodologia().getMetodo() == null ? "" : atvprep.getMetodologia().getMetodo())),
                atvprep.getLote_preparo(),
                atvprep.getCromatografo().getSystem_name(),
                atvprep.getData_hora_fim() == null ? "Em Preparo" : "Finalizado",
                DataHora.getStringDateTime(atvprep.getData_hora_registro()),
                atvprep.getUser_registro().getUser()
            });
        }
    }
}
