/*
 * Copyright (C) 2018 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package Frm.Programacao;

import Classes.DAO.AnaliseCromatografoDAO;
import Classes.Modelo.AnaliseCromatografo;
import Classes.Util.DataHora;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public class FrmLotesEquipamento extends javax.swing.JDialog {

    /**
     * Creates new form FrmLotesEquipamento
     */
    public FrmLotesEquipamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Lotes - Equipamento");
        readLotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLotesEquipamento = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPesquisarLote = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        btnAtualizarLotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("Pesquisar:");

        txtPesquisarLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarLoteKeyReleased(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Lotes"));

        tblLotes.setAutoCreateRowSorter(true);
        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Produto", "Análise", "Lote", "Campanha", "Status", "Equipamento", "Data Registro", "Analista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLotes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblLotes.setSurrendersFocusOnKeystroke(true);
        tblLotes.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(tblLotes);
        if (tblLotes.getColumnModel().getColumnCount() > 0) {
            tblLotes.getColumnModel().getColumn(0).setMinWidth(0);
            tblLotes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblLotes.getColumnModel().getColumn(0).setMaxWidth(0);
            tblLotes.getColumnModel().getColumn(1).setMinWidth(500);
            tblLotes.getColumnModel().getColumn(1).setPreferredWidth(500);
            tblLotes.getColumnModel().getColumn(1).setMaxWidth(500);
            tblLotes.getColumnModel().getColumn(2).setMinWidth(220);
            tblLotes.getColumnModel().getColumn(2).setPreferredWidth(220);
            tblLotes.getColumnModel().getColumn(2).setMaxWidth(220);
            tblLotes.getColumnModel().getColumn(3).setMinWidth(150);
            tblLotes.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblLotes.getColumnModel().getColumn(3).setMaxWidth(150);
            tblLotes.getColumnModel().getColumn(4).setMinWidth(300);
            tblLotes.getColumnModel().getColumn(4).setPreferredWidth(300);
            tblLotes.getColumnModel().getColumn(4).setMaxWidth(300);
            tblLotes.getColumnModel().getColumn(5).setMinWidth(100);
            tblLotes.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblLotes.getColumnModel().getColumn(5).setMaxWidth(100);
            tblLotes.getColumnModel().getColumn(6).setMinWidth(100);
            tblLotes.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblLotes.getColumnModel().getColumn(6).setMaxWidth(100);
            tblLotes.getColumnModel().getColumn(7).setMinWidth(150);
            tblLotes.getColumnModel().getColumn(7).setPreferredWidth(150);
            tblLotes.getColumnModel().getColumn(7).setMaxWidth(150);
            tblLotes.getColumnModel().getColumn(8).setMinWidth(120);
            tblLotes.getColumnModel().getColumn(8).setPreferredWidth(120);
            tblLotes.getColumnModel().getColumn(8).setMaxWidth(120);
        }

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        btnAtualizarLotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_raio.png"))); // NOI18N
        btnAtualizarLotes.setText("Atualizar");
        btnAtualizarLotes.setToolTipText("Atualizar");
        btnAtualizarLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarLotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLotesEquipamentoLayout = new javax.swing.GroupLayout(pnlLotesEquipamento);
        pnlLotesEquipamento.setLayout(pnlLotesEquipamentoLayout);
        pnlLotesEquipamentoLayout.setHorizontalGroup(
            pnlLotesEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLotesEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLotesEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLotesEquipamentoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarLote))
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLotesEquipamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtualizarLotes)))
                .addContainerGap())
        );
        pnlLotesEquipamentoLayout.setVerticalGroup(
            pnlLotesEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLotesEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLotesEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarLotes)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLotesEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLotesEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarLoteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarLoteKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblLotes.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblLotes.setRowSorter(sorter);
        String text = txtPesquisarLote.getText().trim().toUpperCase();
        String parametro = "*";
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_txtPesquisarLoteKeyReleased

    private void btnAtualizarLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarLotesActionPerformed
        readLotes();
    }//GEN-LAST:event_btnAtualizarLotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLotesEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLotesEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLotesEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLotesEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLotesEquipamento dialog = new FrmLotesEquipamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarLotes;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlLotesEquipamento;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField txtPesquisarLote;
    // End of variables declaration//GEN-END:variables


    private void readLotes() {
        DefaultTableModel model = (DefaultTableModel) tblLotes.getModel();
        AnaliseCromatografoDAO anlscroDao = new AnaliseCromatografoDAO();
        model.setNumRows(0);
        for (AnaliseCromatografo anlscro : anlscroDao.readAnaliseCromatografo()) {
            model.addRow(new Object[]{
                anlscro.getLog_lote_id(),
                anlscro.getMaterial().getNome_material(),
                anlscro.getAnalise().getAnalise(),
                anlscro.getLote().getLote_produto(),
                anlscro.getCampanha().getNome_campanha(),
                anlscro.getStatus(),
                anlscro.getCromatografo().getSystem_name(),
                DataHora.getStringDateTime(anlscro.getData_hora_registro()),
                anlscro.getUser_registro().getUser()
            });
        }
    }
}
