/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Programacao;

import Classes.DAO.AnaliseDAO;
import Classes.DAO.CampanhaDAO;
import Classes.DAO.CromatografoDAO;
import Classes.DAO.MetodologiaDAO;
import Classes.DAO.SetorDAO;
import Frm.Login.FrmSalvar;
import Classes.Modelo.Analise;
import Classes.Modelo.Campanha;
import Classes.Modelo.Cromatografo;
import Classes.Modelo.Metodologia;
import Classes.Modelo.Setor;
import Classes.Util.ComboBox;
import Classes.Util.DataHora;
import java.awt.Cursor;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.RowFilter;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public final class FrmNovoCampanhaCromatografo extends javax.swing.JDialog {

    private int novoMetodologia = 0;
    private boolean editar;
    private boolean editar_campanha;
    private Integer campanha_id;
    private TreeMap<Integer, String> categoryMapAnalise = new TreeMap<>();

    /**
     * Creates new form FrmNovoRegistroCromatografo
     *
     * @param parent
     * @param modal
     * @param camp_id
     */
    public FrmNovoCampanhaCromatografo(java.awt.Frame parent,
            boolean modal, Integer camp_id) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        loadDataHora();
        readEquipamento();
        readSetorCampanhas();
        readAnalise();
        readCor();
        fecharDados();
        if (camp_id > 0) {
            setTitle("Editar Campanha");
            carregarDados(camp_id);
            campanha_id = camp_id;
            editar = true;
        } else {
            setTitle("Nova Campanha");
            editar = false;
        }
    }

    public FrmNovoCampanhaCromatografo(java.awt.Frame parent, boolean modal,
            Integer camp_id, Boolean edit_campanha) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        loadDataHora();
        readEquipamento();
        readSetorCampanhas();
        readAnalise();
        readCor();
        fecharDados();
        editar_campanha = edit_campanha;
        setTitle("Editar Campanha");
        carregarDados(camp_id);
        campanha_id = camp_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistros = new javax.swing.JTabbedPane();
        pnlDados = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtMetodo1 = new javax.swing.JTextField();
        btnAdicionarMetodo1 = new javax.swing.JButton();
        btnRemoverMetodo1 = new javax.swing.JButton();
        btnAdicionarMetodo2 = new javax.swing.JButton();
        btnRemoverMetodo2 = new javax.swing.JButton();
        btnAdicionarMetodo3 = new javax.swing.JButton();
        btnRemoverMetodo3 = new javax.swing.JButton();
        btnAdicionarMetodo4 = new javax.swing.JButton();
        btnRemoverMetodo4 = new javax.swing.JButton();
        txtMetodo4 = new javax.swing.JTextField();
        txtMetodo2 = new javax.swing.JTextField();
        txtMetodo3 = new javax.swing.JTextField();
        txtCodMetodo1 = new javax.swing.JTextField();
        txtCodMetodo2 = new javax.swing.JTextField();
        txtCodMetodo3 = new javax.swing.JTextField();
        txtCodMetodo4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCampanha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cmbEquipamento = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        cmbSetorCampanhas = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmbAnalise = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        txtDataPrevisao = new com.toedter.calendar.JDateChooser();
        txtHora = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        txtMinuto = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbCor = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        pnlMetodologia = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMetodologia = new javax.swing.JTable();
        txtPesquisarMetodologia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvarMetodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Metodologia"));

        txtMetodo1.setEditable(false);
        txtMetodo1.setBackground(new java.awt.Color(204, 204, 204));
        txtMetodo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnAdicionarMetodo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdicionarMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMetodo1ActionPerformed(evt);
            }
        });

        btnRemoverMetodo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnRemoverMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMetodo1ActionPerformed(evt);
            }
        });

        btnAdicionarMetodo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdicionarMetodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMetodo2ActionPerformed(evt);
            }
        });

        btnRemoverMetodo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnRemoverMetodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMetodo2ActionPerformed(evt);
            }
        });

        btnAdicionarMetodo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdicionarMetodo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMetodo3ActionPerformed(evt);
            }
        });

        btnRemoverMetodo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnRemoverMetodo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMetodo3ActionPerformed(evt);
            }
        });

        btnAdicionarMetodo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdicionarMetodo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMetodo4ActionPerformed(evt);
            }
        });

        btnRemoverMetodo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnRemoverMetodo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMetodo4ActionPerformed(evt);
            }
        });

        txtMetodo4.setEditable(false);
        txtMetodo4.setBackground(new java.awt.Color(204, 204, 204));
        txtMetodo4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtMetodo2.setEditable(false);
        txtMetodo2.setBackground(new java.awt.Color(204, 204, 204));
        txtMetodo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtMetodo3.setEditable(false);
        txtMetodo3.setBackground(new java.awt.Color(204, 204, 204));
        txtMetodo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtCodMetodo1.setEditable(false);
        txtCodMetodo1.setBackground(new java.awt.Color(204, 204, 204));
        txtCodMetodo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtCodMetodo2.setEditable(false);
        txtCodMetodo2.setBackground(new java.awt.Color(204, 204, 204));
        txtCodMetodo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtCodMetodo3.setEditable(false);
        txtCodMetodo3.setBackground(new java.awt.Color(204, 204, 204));
        txtCodMetodo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtCodMetodo4.setEditable(false);
        txtCodMetodo4.setBackground(new java.awt.Color(204, 204, 204));
        txtCodMetodo4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodMetodo1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtCodMetodo3)
                    .addComponent(txtCodMetodo2)
                    .addComponent(txtCodMetodo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMetodo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMetodo2)
                            .addComponent(txtMetodo3)
                            .addComponent(txtMetodo4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdicionarMetodo4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoverMetodo4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdicionarMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoverMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdicionarMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoverMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionarMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemoverMetodo1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRemoverMetodo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRemoverMetodo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRemoverMetodo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarMetodo4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMetodo4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodMetodo4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Campanha"));

        jLabel2.setText("Obs:");

        jLabel1.setText("Nome:");

        jLabel25.setText("Equipamento:");

        jLabel27.setText("Setor:");

        jLabel8.setText("Análise:");

        jLabel26.setText("Previsão:");

        jLabel12.setText("h");

        jLabel13.setText("min");

        jLabel22.setText("Prioridade:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCampanha)
                    .addComponent(txtObs)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbSetorCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEquipamento, 0, 247, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDataPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSetorCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(cmbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel22)
                        .addComponent(cmbCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pnlRegistros.addTab("Dados", pnlDados);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Metodologias"));

        tblMetodologia.setAutoCreateRowSorter(true);
        tblMetodologia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Código", "Método", "Versão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMetodologia.setSurrendersFocusOnKeystroke(true);
        tblMetodologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMetodologiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMetodologia);
        if (tblMetodologia.getColumnModel().getColumnCount() > 0) {
            tblMetodologia.getColumnModel().getColumn(0).setMinWidth(50);
            tblMetodologia.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblMetodologia.getColumnModel().getColumn(0).setMaxWidth(50);
            tblMetodologia.getColumnModel().getColumn(1).setMinWidth(120);
            tblMetodologia.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblMetodologia.getColumnModel().getColumn(1).setMaxWidth(120);
            tblMetodologia.getColumnModel().getColumn(3).setMinWidth(100);
            tblMetodologia.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblMetodologia.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );

        txtPesquisarMetodologia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarMetodologiaKeyReleased(evt);
            }
        });

        jLabel4.setText("Pesquisar:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvarMetodo.setText("Ok");
        btnSalvarMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMetodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMetodologiaLayout = new javax.swing.GroupLayout(pnlMetodologia);
        pnlMetodologia.setLayout(pnlMetodologiaLayout);
        pnlMetodologiaLayout.setHorizontalGroup(
            pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetodologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMetodologiaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarMetodologia))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMetodologiaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMetodologiaLayout.setVerticalGroup(
            pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetodologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvarMetodo))
                .addGap(16, 16, 16))
        );

        pnlRegistros.addTab("Metodologias", pnlMetodologia);

        getContentPane().add(pnlRegistros);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMetodologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMetodologiaMouseClicked
        if (evt.getClickCount() == 2) {
            carregarDados(tblMetodologia.getValueAt(tblMetodologia.getSelectedRow(), 0).toString(),
                    tblMetodologia.getValueAt(tblMetodologia.getSelectedRow(), 1).toString() + " - "
                    + tblMetodologia.getValueAt(tblMetodologia.getSelectedRow(), 2).toString());
            novoMetodologia = 0;
            fecharDados();
        }
    }//GEN-LAST:event_tblMetodologiaMouseClicked

    private void txtPesquisarMetodologiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarMetodologiaKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblMetodologia.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblMetodologia.setRowSorter(sorter);
        String text = txtPesquisarMetodologia.getText().trim();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_txtPesquisarMetodologiaKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fecharDados();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMetodoActionPerformed
        if (tblMetodologia.getSelectedRow() != -1) {
            carregarDados(tblMetodologia.getValueAt(tblMetodologia.getSelectedRow(), 0).toString(),
                    tblMetodologia.getValueAt(tblMetodologia.getSelectedRow(), 1).toString() + " - "
                    + tblMetodologia.getValueAt(tblMetodologia.getSelectedRow(), 2).toString());
            novoMetodologia = 0;
            fecharDados();
        }
    }//GEN-LAST:event_btnSalvarMetodoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNomeCampanha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome da Campanha inválido");
            txtNomeCampanha.requestFocus();
        } else if (cmbSetorCampanhas.getSelectedItem() == null
                ? true : cmbSetorCampanhas.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Setor inválido");
            cmbSetorCampanhas.requestFocus();
        } else if (cmbAnalise.getSelectedItem() == null
                ? true : cmbAnalise.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Análise inválida");
            cmbAnalise.requestFocus();
        } else {
            StringBuilder sb = new StringBuilder();
            sb.append("a").append(txtCodMetodo1.getText());
            sb.append("b").append(txtCodMetodo2.getText());
            sb.append("c").append(txtCodMetodo3.getText());
            sb.append("d").append(txtCodMetodo4.getText());
            FrmSalvar frmSalvar = new FrmSalvar(null, true);
            frmSalvar.setVisible(true);
            if (frmSalvar.senha()) {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                if (editar || editar_campanha) {
                    atualizarCampanha(sb.toString());
                } else {
                    criarCampanha(sb.toString());
                }
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)
                );
                dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAdicionarMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMetodo1ActionPerformed
        novoMetodologia = 1;
        carregarMetodo();
    }//GEN-LAST:event_btnAdicionarMetodo1ActionPerformed

    private void btnAdicionarMetodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMetodo2ActionPerformed
        novoMetodologia = 2;
        carregarMetodo();
    }//GEN-LAST:event_btnAdicionarMetodo2ActionPerformed

    private void btnAdicionarMetodo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMetodo3ActionPerformed
        novoMetodologia = 3;
        carregarMetodo();
    }//GEN-LAST:event_btnAdicionarMetodo3ActionPerformed

    private void btnAdicionarMetodo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMetodo4ActionPerformed
        novoMetodologia = 4;
        carregarMetodo();
    }//GEN-LAST:event_btnAdicionarMetodo4ActionPerformed

    private void btnRemoverMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMetodo1ActionPerformed
        txtCodMetodo1.setText("");
        txtMetodo1.setText("");
    }//GEN-LAST:event_btnRemoverMetodo1ActionPerformed

    private void btnRemoverMetodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMetodo2ActionPerformed
        txtCodMetodo2.setText("");
        txtMetodo2.setText("");
    }//GEN-LAST:event_btnRemoverMetodo2ActionPerformed

    private void btnRemoverMetodo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMetodo3ActionPerformed
        txtCodMetodo3.setText("");
        txtMetodo3.setText("");
    }//GEN-LAST:event_btnRemoverMetodo3ActionPerformed

    private void btnRemoverMetodo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMetodo4ActionPerformed
        txtCodMetodo4.setText("");
        txtMetodo4.setText("");
    }//GEN-LAST:event_btnRemoverMetodo4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNovoCampanhaCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNovoCampanhaCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNovoCampanhaCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNovoCampanhaCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmNovoCampanhaCromatografo dialog = new FrmNovoCampanhaCromatografo(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarMetodo1;
    private javax.swing.JButton btnAdicionarMetodo2;
    private javax.swing.JButton btnAdicionarMetodo3;
    private javax.swing.JButton btnAdicionarMetodo4;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRemoverMetodo1;
    private javax.swing.JButton btnRemoverMetodo2;
    private javax.swing.JButton btnRemoverMetodo3;
    private javax.swing.JButton btnRemoverMetodo4;
    public static javax.swing.JButton btnSalvar;
    public static javax.swing.JButton btnSalvarMetodo;
    private javax.swing.JComboBox cmbAnalise;
    private javax.swing.JComboBox cmbCor;
    private javax.swing.JComboBox cmbEquipamento;
    private javax.swing.JComboBox cmbSetorCampanhas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlMetodologia;
    private javax.swing.JTabbedPane pnlRegistros;
    private javax.swing.JTable tblMetodologia;
    private javax.swing.JTextField txtCodMetodo1;
    private javax.swing.JTextField txtCodMetodo2;
    private javax.swing.JTextField txtCodMetodo3;
    private javax.swing.JTextField txtCodMetodo4;
    private com.toedter.calendar.JDateChooser txtDataPrevisao;
    private javax.swing.JSpinner txtHora;
    private javax.swing.JTextField txtMetodo1;
    private javax.swing.JTextField txtMetodo2;
    private javax.swing.JTextField txtMetodo3;
    private javax.swing.JTextField txtMetodo4;
    private javax.swing.JSpinner txtMinuto;
    private javax.swing.JTextField txtNomeCampanha;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtPesquisarMetodologia;
    // End of variables declaration//GEN-END:variables

    private void loadDataHora() {
        SpinnerNumberModel modelHoraFim = new SpinnerNumberModel(0, 0, 23, 1);
        txtHora.setModel(modelHoraFim);
        JSpinner.NumberEditor editorHoraFim = new JSpinner.NumberEditor(txtHora);
        txtHora.setEditor(editorHoraFim);
        SpinnerNumberModel modelMinutoFim = new SpinnerNumberModel(0, 0, 59, 1);
        txtMinuto.setModel(modelMinutoFim);
        JSpinner.NumberEditor editorMinutoFim = new JSpinner.NumberEditor(txtMinuto);
        txtMinuto.setEditor(editorMinutoFim);
        Date currentDate = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(currentDate);
        txtDataPrevisao.setDate(cal.getTime());
        txtHora.setValue((Integer) cal.get(Calendar.HOUR_OF_DAY));
        txtMinuto.setValue((Integer) cal.get(Calendar.MINUTE));
    }

    public final void readMetodologia() {
        DefaultTableModel model = (DefaultTableModel) tblMetodologia.getModel();
        MetodologiaDAO equipDao = new MetodologiaDAO();
        model.setNumRows(0);
        for (Metodologia mtd : equipDao.readMetodologia()) {
            model.addRow(new Object[]{
                mtd.getMetodo_id(),
                mtd.getCod_metodo(),
                mtd.getMetodo(),
                mtd.getVersao()
            });
        }
    }

    public final void readAnalise() {
        cmbAnalise.removeAllItems();
        cmbAnalise.addItem("");
        categoryMapAnalise.clear();
        AnaliseDAO anlsDao = new AnaliseDAO();
        for (Analise anls : anlsDao.readAnalise()) {
            Integer id_analise = anls.getAnalise_id();
            String name = anls.getAnalise();
            cmbAnalise.addItem(name);
            categoryMapAnalise.put(id_analise, name);
        }
    }

    private void carregarMetodo() {
        readMetodologia();
        pnlRegistros.setEnabledAt(0, false);
        pnlRegistros.setEnabledAt(1, true);
        pnlRegistros.setSelectedIndex(1);
    }

    private void carregarDados(String cod, String metodo) {
        switch (novoMetodologia) {
            case 1:
                txtCodMetodo1.setText(cod);
                txtMetodo1.setText(metodo);
                break;
            case 2:
                txtCodMetodo2.setText(cod);
                txtMetodo2.setText(metodo);
                break;
            case 3:
                txtCodMetodo3.setText(cod);
                txtMetodo3.setText(metodo);
                break;
            case 4:
                txtCodMetodo4.setText(cod);
                txtMetodo4.setText(metodo);
                break;
        }
    }

    private void fecharDados() {
        pnlRegistros.setEnabledAt(0, true);
        pnlRegistros.setEnabledAt(1, false);
        pnlRegistros.setSelectedIndex(0);
    }

    private void criarCampanha(String metodos) {
        try {
            Campanha camp = new Campanha();
            CampanhaDAO campDAO = new CampanhaDAO();
            Cromatografo equip = new Cromatografo();
            Analise anls = new Analise();
            Setor setor = new Setor();
            camp.setNome_campanha(txtNomeCampanha.getText().toUpperCase());
            camp.setMetodos(metodos);
            equip.setSystem_name(cmbEquipamento.getSelectedItem() != null
                    ? cmbEquipamento.getSelectedItem().toString() : "");
            camp.setCromatografo(equip);
            camp.setObs_campanha(txtObs.getText().toUpperCase());
            camp.setOrdem(campDAO.selectUltimaCampanhaByOrdem() + 1);
            setor.setSigla_setor(cmbSetorCampanhas.getSelectedItem() == null ? ""
                    : cmbSetorCampanhas.getSelectedItem().toString());
            camp.setSetor(setor);
            anls.setAnalise_id(ComboBox.getKeyForValue(cmbAnalise.getSelectedItem().toString(), categoryMapAnalise));
            camp.setAnalise(anls);
            Timestamp datahora_previsao = DataHora.getTimestampDateTime(DataHora.getStringDate(txtDataPrevisao.getDate())
                    + " " + txtHora.getValue().toString()
                    + ":" + txtMinuto.getValue().toString() + ":00");
            camp.setPrevisao(datahora_previsao);
            camp.setCor(cmbCor.getSelectedItem().toString());
            campDAO.createCampanhas(camp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        }
    }

    public final void readEquipamento() {
        cmbEquipamento.removeAllItems();
        cmbEquipamento.addItem("");
        CromatografoDAO equipDao = new CromatografoDAO();
        for (Cromatografo equip : equipDao.readCromatografo()) {
            String name = equip.getSystem_name();
            cmbEquipamento.addItem(name);
        }
    }

    public final void readSetorCampanhas() {
        cmbSetorCampanhas.removeAllItems();
        cmbSetorCampanhas.addItem("");
        SetorDAO setorDao = new SetorDAO();
        for (Setor setor : setorDao.readSetor()) {
            if (setor.getSigla_setor().startsWith("HPLC") || setor.getSigla_setor().startsWith("CG")) {
                cmbSetorCampanhas.addItem(setor.getSigla_setor());
            }
        }
    }

    public final void carregarDados(Integer campanha_id) {
        Campanha camp = new Campanha();
        CampanhaDAO campDAO = new CampanhaDAO();
        camp.setLog_campanha_id(campanha_id);
        campDAO.selectCampanhaById(camp);
        txtNomeCampanha.setText(camp.getNome_campanha());
        txtObs.setText(camp.getObs_campanha());
        String[] setores = {camp.getSetor().getSigla_setor()};
        cmbSetorCampanhas.setSelectedItem(setores[0]);
        String[] equipamento = {camp.getCromatografo().getSystem_name()};
        cmbEquipamento.setSelectedItem(equipamento[0]);
        String[] analise = {camp.getAnalise().getAnalise()};
        cmbAnalise.setSelectedItem(analise[0]);
        String[] cor = {camp.getCor()};
        cmbCor.setSelectedItem(cor[0]);
        Calendar cal = Calendar.getInstance();
        cal.setTime(camp.getPrevisao() == null ? new Date() : camp.getPrevisao());
        txtDataPrevisao.setDate(camp.getPrevisao());
        txtHora.setValue((Integer) cal.get(Calendar.HOUR_OF_DAY));
        txtMinuto.setValue((Integer) cal.get(Calendar.MINUTE));
        String text = camp.getMetodos();
        String a = "a";
        String b = "b";
        String c = "c";
        String d = "d";
        MetodologiaDAO mtdDAO = new MetodologiaDAO();
        txtCodMetodo1.setText(text.substring(text.indexOf(a) + 1, text.indexOf(b)));
        txtMetodo1.setText(mtdDAO.selectMetodologiaById(Integer.parseInt(text.substring(text.indexOf(a) + 1, text.indexOf(b)))));
        txtCodMetodo2.setText(text.substring(text.indexOf(b) + 1, text.indexOf(c)));
        txtMetodo2.setText(mtdDAO.selectMetodologiaById(Integer.parseInt(text.substring(text.indexOf(b) + 1, text.indexOf(c)))));
        txtCodMetodo3.setText(text.substring(text.indexOf(c) + 1, text.indexOf(d)));
        txtMetodo3.setText(mtdDAO.selectMetodologiaById(Integer.parseInt(text.substring(text.indexOf(c) + 1, text.indexOf(d)))));
        txtCodMetodo4.setText(text.substring(text.indexOf(d) + 1, text.length()));
        txtMetodo4.setText(mtdDAO.selectMetodologiaById(Integer.parseInt(text.substring(text.indexOf(d) + 1, text.length()))));
        if (editar_campanha) {
            cmbEquipamento.setEnabled(false);
        } else {
            cmbEquipamento.setEnabled(true);
        }
    }

    private void atualizarCampanha(String metodos) {
        try {
            Campanha camp = new Campanha();
            CampanhaDAO campDAO = new CampanhaDAO();
            Cromatografo equip = new Cromatografo();
            Setor setor = new Setor();
            Analise anls = new Analise();
            camp.setLog_campanha_id(campanha_id);
            camp.setNome_campanha(txtNomeCampanha.getText().toUpperCase());
            camp.setMetodos(metodos);
            equip.setSystem_name(cmbEquipamento.getSelectedItem() != null
                    ? cmbEquipamento.getSelectedItem().toString() : "");
            camp.setCromatografo(equip);
            camp.setObs_campanha(txtObs.getText().toUpperCase());
            setor.setSigla_setor(cmbSetorCampanhas.getSelectedItem() == null ? ""
                    : cmbSetorCampanhas.getSelectedItem().toString());
            camp.setSetor(setor);
            anls.setAnalise_id(ComboBox.getKeyForValue(cmbAnalise.getSelectedItem().toString(), categoryMapAnalise));
            camp.setAnalise(anls);
            Timestamp datahora_previsao = DataHora.getTimestampDateTime(DataHora.getStringDate(txtDataPrevisao.getDate())
                    + " " + txtHora.getValue().toString()
                    + ":" + txtMinuto.getValue().toString() + ":00");
            camp.setPrevisao(datahora_previsao);
            camp.setCor(cmbCor.getSelectedItem().toString());
            campDAO.updateCampanhas(camp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        }
    }

    public final void readCor() {
        cmbCor.removeAllItems();
        cmbCor.addItem("");
        cmbCor.addItem("Roxo");
        cmbCor.addItem("Vermelho");
        cmbCor.addItem("Rosa");
        cmbCor.addItem("Laranja");
        cmbCor.addItem("Amarelo");
    }

}
