/*
 * Copyright (C) 2018 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package Frm.Programacao;

import Classes.DAO.TrocaTurnoDAO;
import Frm.Hplc.FrmTrocaTurno;
import Classes.Modelo.TrocaTurno;
import Classes.Util.DataHora;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public class FrmPassagemTurno extends javax.swing.JDialog {

    /**
     * Creates new form FrmLotesEquipamento
     */
    public FrmPassagemTurno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Passagem de Turno");
        readTrocaTurno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisarTrocaTurno = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTrocaTurno = new javax.swing.JTable();
        btnAtualizarPreparo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Pesquisar:");

        txtPesquisarTrocaTurno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarTrocaTurnoKeyReleased(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Trocas de Turno"));

        tblTrocaTurno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Turno", "Equipamento", "Campanha", "Descrição", "Data", "Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTrocaTurno.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTrocaTurno.setSurrendersFocusOnKeystroke(true);
        tblTrocaTurno.getTableHeader().setReorderingAllowed(false);
        tblTrocaTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrocaTurnoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblTrocaTurno);
        if (tblTrocaTurno.getColumnModel().getColumnCount() > 0) {
            tblTrocaTurno.getColumnModel().getColumn(0).setMinWidth(0);
            tblTrocaTurno.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblTrocaTurno.getColumnModel().getColumn(0).setMaxWidth(0);
            tblTrocaTurno.getColumnModel().getColumn(1).setMinWidth(80);
            tblTrocaTurno.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblTrocaTurno.getColumnModel().getColumn(1).setMaxWidth(80);
            tblTrocaTurno.getColumnModel().getColumn(2).setMinWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(2).setMaxWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(3).setMinWidth(300);
            tblTrocaTurno.getColumnModel().getColumn(3).setPreferredWidth(300);
            tblTrocaTurno.getColumnModel().getColumn(3).setMaxWidth(300);
            tblTrocaTurno.getColumnModel().getColumn(4).setMinWidth(500);
            tblTrocaTurno.getColumnModel().getColumn(4).setPreferredWidth(500);
            tblTrocaTurno.getColumnModel().getColumn(4).setMaxWidth(500);
            tblTrocaTurno.getColumnModel().getColumn(5).setMinWidth(150);
            tblTrocaTurno.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblTrocaTurno.getColumnModel().getColumn(5).setMaxWidth(150);
            tblTrocaTurno.getColumnModel().getColumn(6).setMinWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblTrocaTurno.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        btnAtualizarPreparo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_raio.png"))); // NOI18N
        btnAtualizarPreparo1.setText("Atualizar");
        btnAtualizarPreparo1.setToolTipText("Atualizar");
        btnAtualizarPreparo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarPreparo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtualizarPreparo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarTrocaTurno))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarTrocaTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarPreparo1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarTrocaTurnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarTrocaTurnoKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblTrocaTurno.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblTrocaTurno.setRowSorter(sorter);
        String text = txtPesquisarTrocaTurno.getText().trim().toUpperCase();
        String parametro = "*";
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text.toUpperCase()));
        }
    }//GEN-LAST:event_txtPesquisarTrocaTurnoKeyReleased

    private void tblTrocaTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrocaTurnoMouseClicked
        if (evt.getClickCount() == 2) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            FrmTrocaTurno frm = new FrmTrocaTurno(null, true,
                tblTrocaTurno.getValueAt(tblTrocaTurno.getSelectedRow(), 2).toString(),
                (Integer) tblTrocaTurno.getValueAt(tblTrocaTurno.getSelectedRow(), 0));
            frm.setVisible(true);
            readTrocaTurno();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_tblTrocaTurnoMouseClicked

    private void btnAtualizarPreparo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarPreparo1ActionPerformed
        readTrocaTurno();
    }//GEN-LAST:event_btnAtualizarPreparo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPassagemTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPassagemTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPassagemTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPassagemTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPassagemTurno dialog = new FrmPassagemTurno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarPreparo1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblTrocaTurno;
    private javax.swing.JTextField txtPesquisarTrocaTurno;
    // End of variables declaration//GEN-END:variables


    private void readTrocaTurno() {
        DefaultTableModel model = (DefaultTableModel) tblTrocaTurno.getModel();
        TrocaTurnoDAO turnoDao = new TrocaTurnoDAO();
        model.setNumRows(0);
        for (TrocaTurno turno : turnoDao.readTrocaTurno()) {
            model.addRow(new Object[]{
                turno.getTroca_turno_id(),
                turno.getTurno(),
                turno.getCromatografo().getSystem_name(),
                turno.getCampanha().getNome_campanha(),
                turno.getDescricao_turno() + "...",
                DataHora.getStringDateTime(turno.getData_registro()),
                turno.getUser_name().getUser()
            });
        }
    }
}
