/*
 * Copyright (C) 2018 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Programacao;

import Classes.DAO.CampanhaDAO;
import Classes.DAO.SetorDAO;
import Classes.Modelo.Campanha;
import Classes.Modelo.Setor;
import Classes.Util.DataHora;
import Classes.Util.GridlineCellRenderer;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmTelaCheiaCampanhas extends javax.swing.JFrame {

    private Timer timer;
    private String fonte;
    private int fonte_size;

    /**
     * Creates new form FrmTelaCheiaEquipamento
     */
    public FrmTelaCheiaCampanhas() {
        initComponents();
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        readSetorPesquisar();
        readCampanhas();
        iniciarContagem();
        setBounds(0, 0, getToolkit().getScreenSize().width, getToolkit().getScreenSize().height);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setSize(getToolkit().getScreenSize().width, getToolkit().getScreenSize().height);
        fonte = tblCampanhas.getFont().getFontName();
        fonte_size = tblCampanhas.getFont().getSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEquipamentos = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        cmbPesquisarSetorCampanha = new javax.swing.JComboBox();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        btnAumentarFonte = new javax.swing.JButton();
        btnDiminuirFonte = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        btnAtualizarEquipamento = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        btnFecharTelaCheia = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblCampanhas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisarCampanhas = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cmbCampoPesquisar = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel25.setText("Setor:");

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_font_size.png"))); // NOI18N
        jToolBar2.add(jLabel1);

        btnAumentarFonte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_ordem_ascendente.png"))); // NOI18N
        btnAumentarFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarFonteActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAumentarFonte);

        btnDiminuirFonte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_ordem_descendente.png"))); // NOI18N
        btnDiminuirFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirFonteActionPerformed(evt);
            }
        });
        jToolBar2.add(btnDiminuirFonte);
        jToolBar2.add(jSeparator14);

        btnAtualizarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_raio.png"))); // NOI18N
        btnAtualizarEquipamento.setToolTipText("Atualizar");
        btnAtualizarEquipamento.setFocusable(false);
        btnAtualizarEquipamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizarEquipamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarEquipamentoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAtualizarEquipamento);
        jToolBar2.add(jSeparator15);

        btnFecharTelaCheia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancel.png"))); // NOI18N
        btnFecharTelaCheia.setToolTipText("Atualizar");
        btnFecharTelaCheia.setFocusable(false);
        btnFecharTelaCheia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharTelaCheiaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnFecharTelaCheia);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Campanhas"));

        tblCampanhas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCampanhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cor", "Ordem", "Id", "Campanha", "Análise", "Equipamento", "Setor", "Previsão", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCampanhas.setSurrendersFocusOnKeystroke(true);
        tblCampanhas.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(tblCampanhas);
        if (tblCampanhas.getColumnModel().getColumnCount() > 0) {
            tblCampanhas.getColumnModel().getColumn(0).setMinWidth(0);
            tblCampanhas.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblCampanhas.getColumnModel().getColumn(0).setMaxWidth(0);
            tblCampanhas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblCampanhas.getColumnModel().getColumn(2).setMinWidth(0);
            tblCampanhas.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblCampanhas.getColumnModel().getColumn(2).setMaxWidth(0);
            tblCampanhas.getColumnModel().getColumn(3).setPreferredWidth(300);
            tblCampanhas.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblCampanhas.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblCampanhas.getColumnModel().getColumn(6).setPreferredWidth(300);
            tblCampanhas.getColumnModel().getColumn(7).setPreferredWidth(150);
            tblCampanhas.getColumnModel().getColumn(8).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        jLabel10.setText("Pesquisar:");

        txtPesquisarCampanhas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarCampanhasKeyReleased(evt);
            }
        });

        jLabel28.setText("Campo:");

        cmbCampoPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Campanha", "Análise", "Equipamento", "Prioridade" }));

        javax.swing.GroupLayout pnlEquipamentosLayout = new javax.swing.GroupLayout(pnlEquipamentos);
        pnlEquipamentos.setLayout(pnlEquipamentosLayout);
        pnlEquipamentosLayout.setHorizontalGroup(
            pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarCampanhas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPesquisarSetorCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlEquipamentosLayout.setVerticalGroup(
            pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipamentosLayout.createSequentialGroup()
                .addGroup(pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbPesquisarSetorCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesquisarCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addGroup(pnlEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlEquipamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlEquipamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharTelaCheiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharTelaCheiaActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharTelaCheiaActionPerformed

    private void btnAtualizarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarEquipamentoActionPerformed
        readCampanhas();
    }//GEN-LAST:event_btnAtualizarEquipamentoActionPerformed

    private void btnAumentarFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarFonteActionPerformed
        tblCampanhas.setFont(new Font(fonte, Font.PLAIN, fonte_size + 1));
        tblCampanhas.setRowHeight(fonte_size + 2);
        fonte_size = fonte_size + 1;
        repaint();
    }//GEN-LAST:event_btnAumentarFonteActionPerformed

    private void btnDiminuirFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiminuirFonteActionPerformed
        tblCampanhas.setFont(new Font(fonte, Font.PLAIN, fonte_size - 1));
        tblCampanhas.setRowHeight(fonte_size - 2);
        fonte_size = fonte_size - 1;
        repaint();
    }//GEN-LAST:event_btnDiminuirFonteActionPerformed

    private void txtPesquisarCampanhasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarCampanhasKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            readCampanhas();
        }
    }//GEN-LAST:event_txtPesquisarCampanhasKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCheiaCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCheiaCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCheiaCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCheiaCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaCheiaCampanhas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarEquipamento;
    private javax.swing.JButton btnAumentarFonte;
    private javax.swing.JButton btnDiminuirFonte;
    private javax.swing.JButton btnFecharTelaCheia;
    private javax.swing.JComboBox cmbCampoPesquisar;
    private javax.swing.JComboBox cmbPesquisarSetorCampanha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel pnlEquipamentos;
    private javax.swing.JTable tblCampanhas;
    private javax.swing.JTextField txtPesquisarCampanhas;
    // End of variables declaration//GEN-END:variables

    private void iniciarContagem() {
        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                readCampanhas();
            }
        };
        this.timer = new Timer(30000, action);
        this.timer.start();
    }
    
    private void readCampanhas() {
        try {
            GridlineCellRenderer r = new GridlineCellRenderer(1, 2, 3, 4, 5, 6, 7, 8, 9);
            DefaultTableModel model = (DefaultTableModel) tblCampanhas.getModel();
            tblCampanhas.setDefaultRenderer(Object.class, r);
            CampanhaDAO campDao = new CampanhaDAO();
            model.setNumRows(0);
            String setor = cmbPesquisarSetorCampanha.getSelectedItem().toString();
            String campo = cmbCampoPesquisar.getSelectedItem().toString();
            String texto = txtPesquisarCampanhas.getText().trim();
            for (Campanha camp : campDao.selectCampanhaProgramacao(setor, campo, texto)) {
                model.addRow(new Object[]{
                    camp.getCor() == null ? "" : camp.getCor(),
                    camp.getOrdem(),
                    camp.getLog_campanha_id(),
                    camp.getNome_campanha(),
                    camp.getAnalise().getAnalise(),
                    camp.getCromatografo().getSystem_name(),
                    camp.getSetor().getSigla_setor(),
                    DataHora.getStringDateTime(camp.getPrevisao()),
                    camp.getObs_campanha()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        }
    }

    public final void readSetorPesquisar() {
        cmbPesquisarSetorCampanha.removeAllItems();
        cmbPesquisarSetorCampanha.addItem("Todos");
        SetorDAO setorDao = new SetorDAO();
        for (Setor setor : setorDao.readSetor()) {
            if (setor.getSigla_setor().startsWith("HPLC") || setor.getSigla_setor().startsWith("CG")) {
                cmbPesquisarSetorCampanha.addItem(setor.getSigla_setor());
            }
        }
    }
}
