/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Preparo;


/**
 *
 * @author rafael.lopes
 */
public class FrmImprimirRetrabalhoPreparo extends javax.swing.JDialog {

    /**
     * Creates new form FrmAtividades
     */
    public FrmImprimirRetrabalhoPreparo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Imprimir Pedidos de Preparo");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnRetrabalhoDetalhado = new javax.swing.JButton();
        btnRetrabalhos = new javax.swing.JButton();
        btnTratativaRetrabalho = new javax.swing.JButton();
        btnRetrabalhoProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        btnRetrabalhoDetalhado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRetrabalhoDetalhado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_report.png"))); // NOI18N
        btnRetrabalhoDetalhado.setText("Retrabalhos - Detalhado");
        btnRetrabalhoDetalhado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRetrabalhoDetalhado.setIconTextGap(50);
        btnRetrabalhoDetalhado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrabalhoDetalhadoActionPerformed(evt);
            }
        });

        btnRetrabalhos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRetrabalhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_coisas.png"))); // NOI18N
        btnRetrabalhos.setText("Retrabalhos - Geral");
        btnRetrabalhos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRetrabalhos.setIconTextGap(50);
        btnRetrabalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrabalhosActionPerformed(evt);
            }
        });

        btnTratativaRetrabalho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTratativaRetrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_causa_raiz.png"))); // NOI18N
        btnTratativaRetrabalho.setText("Retrabalhos - Motivos");
        btnTratativaRetrabalho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTratativaRetrabalho.setIconTextGap(50);
        btnTratativaRetrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratativaRetrabalhoActionPerformed(evt);
            }
        });

        btnRetrabalhoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRetrabalhoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_produto_1.png"))); // NOI18N
        btnRetrabalhoProduto.setText("Retrabalho - Produto");
        btnRetrabalhoProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRetrabalhoProduto.setIconTextGap(50);
        btnRetrabalhoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrabalhoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetrabalhoDetalhado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetrabalhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTratativaRetrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(btnRetrabalhoProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetrabalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetrabalhoDetalhado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTratativaRetrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetrabalhoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrabalhoDetalhadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrabalhoDetalhadoActionPerformed
        FrmImpressaoRelatorioRetrabalhoDetalhado frm = new FrmImpressaoRelatorioRetrabalhoDetalhado(null, true);
        frm.setVisible(true);
        frm.dispose();
        dispose();
    }//GEN-LAST:event_btnRetrabalhoDetalhadoActionPerformed

    private void btnRetrabalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrabalhosActionPerformed
        FrmImpressaoRelatorioRetrabalho frm = new FrmImpressaoRelatorioRetrabalho(null, true);
        frm.setVisible(true);
        frm.dispose();
        dispose();
    }//GEN-LAST:event_btnRetrabalhosActionPerformed

    private void btnTratativaRetrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratativaRetrabalhoActionPerformed
        FrmImpressaoRelatorioTratativaRetrabalho frm = new FrmImpressaoRelatorioTratativaRetrabalho(null, true);
        frm.setVisible(true);
        frm.dispose();
        dispose();
    }//GEN-LAST:event_btnTratativaRetrabalhoActionPerformed

    private void btnRetrabalhoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrabalhoProdutoActionPerformed
        FrmImpressaoRelatorioRetrabalhoProduto frm = new FrmImpressaoRelatorioRetrabalhoProduto(null, true);
        frm.setVisible(true);
        frm.dispose();
        dispose();
    }//GEN-LAST:event_btnRetrabalhoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmImprimirRetrabalhoPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmImprimirRetrabalhoPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmImprimirRetrabalhoPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmImprimirRetrabalhoPreparo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmImprimirRetrabalhoPreparo dialog = new FrmImprimirRetrabalhoPreparo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetrabalhoDetalhado;
    private javax.swing.JButton btnRetrabalhoProduto;
    private javax.swing.JButton btnRetrabalhos;
    private javax.swing.JButton btnTratativaRetrabalho;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
