/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Frm.Preparo;

import Classes.DAO.AtividadePreparoDAO;
import Classes.Acesso.PedidoPreparoAcesso;
import Classes.Modelo.AtividadePreparo;
import Classes.Util.DataHora;
import Frm.Login.FrmSalvar;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public class FrmPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public FrmPedidos() {
        initComponents();
        setTitle("Pedidos de Preparo");
        readAtividadePreparo();
        PedidoPreparoAcesso Acesso = new PedidoPreparoAcesso();
        Acesso.verificarAcessoPedido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtividadePreparo = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        jToolBar1 = new javax.swing.JToolBar();
        btnPedidosPreparo = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnAtualizar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnImprimirPedidos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnCancelarPedidos = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Atividades"));

        tblAtividadePreparo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Data Registro", "Descrição", "Lote", "Equipamento", "Metodo", "Qtd", "Observação", "Retrabalho", "categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAtividadePreparo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblAtividadePreparo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAtividadePreparoMouseClicked(evt);
            }
        });
        tblAtividadePreparo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAtividadePreparoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblAtividadePreparo);
        if (tblAtividadePreparo.getColumnModel().getColumnCount() > 0) {
            tblAtividadePreparo.getColumnModel().getColumn(0).setMinWidth(0);
            tblAtividadePreparo.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblAtividadePreparo.getColumnModel().getColumn(0).setMaxWidth(0);
            tblAtividadePreparo.getColumnModel().getColumn(1).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblAtividadePreparo.getColumnModel().getColumn(2).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(2).setPreferredWidth(550);
            tblAtividadePreparo.getColumnModel().getColumn(3).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblAtividadePreparo.getColumnModel().getColumn(4).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblAtividadePreparo.getColumnModel().getColumn(5).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(5).setPreferredWidth(600);
            tblAtividadePreparo.getColumnModel().getColumn(6).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(6).setPreferredWidth(50);
            tblAtividadePreparo.getColumnModel().getColumn(7).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(7).setPreferredWidth(250);
            tblAtividadePreparo.getColumnModel().getColumn(8).setResizable(false);
            tblAtividadePreparo.getColumnModel().getColumn(8).setPreferredWidth(80);
            tblAtividadePreparo.getColumnModel().getColumn(9).setMinWidth(0);
            tblAtividadePreparo.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblAtividadePreparo.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        jLabel5.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Análise", "Soluções Reagentes", "System Suitability ", "Atividade Geral" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnPedidosPreparo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_pedido_preparo.png"))); // NOI18N
        btnPedidosPreparo.setText("Pedidos");
        btnPedidosPreparo.setFocusable(false);
        btnPedidosPreparo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPedidosPreparo.setPreferredSize(new java.awt.Dimension(60, 60));
        btnPedidosPreparo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPedidosPreparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosPreparoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPedidosPreparo);
        jToolBar1.add(jSeparator4);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setFocusable(false);
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAtualizar);
        jToolBar1.add(jSeparator6);

        btnImprimirPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_print.png"))); // NOI18N
        btnImprimirPedidos.setText("Imprimir");
        btnImprimirPedidos.setFocusable(false);
        btnImprimirPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirPedidos.setPreferredSize(new java.awt.Dimension(60, 60));
        btnImprimirPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPedidosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirPedidos);
        jToolBar1.add(jSeparator5);

        btnCancelarPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_close.png"))); // NOI18N
        btnCancelarPedidos.setText("Cancelar");
        btnCancelarPedidos.setFocusable(false);
        btnCancelarPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarPedidos.setPreferredSize(new java.awt.Dimension(60, 60));
        btnCancelarPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelarPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAtividadePreparoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAtividadePreparoMouseClicked
        if (evt.getClickCount() == 2) {
            carregarDados();
            readAtividadePreparo();
        }
    }//GEN-LAST:event_tblAtividadePreparoMouseClicked

    private void tblAtividadePreparoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAtividadePreparoKeyPressed
        if (tblAtividadePreparo.getSelectedRow() != -1) {
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                deletarDados((Integer) tblAtividadePreparo.getValueAt(tblAtividadePreparo.getSelectedRow(), 0));
            }
        }
    }//GEN-LAST:event_tblAtividadePreparoKeyPressed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        tableSorter();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnPedidosPreparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosPreparoActionPerformed
        FrmPedidoPreparo frm = new FrmPedidoPreparo(null, true);
        frm.setVisible(true);
        readAtividadePreparo();
    }//GEN-LAST:event_btnPedidosPreparoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        readAtividadePreparo();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCancelarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidosActionPerformed
        if (tblAtividadePreparo.getSelectedRow() != -1) {
            deletarDados((Integer) tblAtividadePreparo.getValueAt(tblAtividadePreparo.getSelectedRow(), 0));
            readAtividadePreparo();
        }
    }//GEN-LAST:event_btnCancelarPedidosActionPerformed

    private void btnImprimirPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPedidosActionPerformed
        FrmImprimirPedidoPreparo frm = new FrmImprimirPedidoPreparo(null, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btnImprimirPedidosActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        tableSorter();
    }//GEN-LAST:event_cmbTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    public static javax.swing.JButton btnCancelarPedidos;
    public static javax.swing.JButton btnImprimirPedidos;
    private javax.swing.JButton btnPedidosPreparo;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblAtividadePreparo;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    private void tableSorter() {
        DefaultTableModel model = (DefaultTableModel) tblAtividadePreparo.getModel();
        TableRowSorter sorter = new TableRowSorter<>(model);
        tblAtividadePreparo.setRowSorter(sorter);
        String text = txtPesquisar.getText().trim();
        String parametro = "*";
        if (text.length() == 0 && "Todos".equals(cmbTipo.getSelectedItem().toString())) {
            sorter.setRowFilter(null);
        } else if (text.indexOf(parametro) > 0 && "Todos".equals(cmbTipo.getSelectedItem().toString())) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else if ("Todos".equals(cmbTipo.getSelectedItem().toString())) {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text.trim().toUpperCase()));
        } else if (text.indexOf(parametro) > 0) {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(0, text.indexOf(parametro)).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter("(?i)" + text.substring(text.indexOf(parametro) + 1, text.length()).trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter(cmbTipo.getSelectedItem().toString()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        } else {
            ArrayList<RowFilter<Object, Object>> andFilters = new ArrayList<>();
            andFilters.add(RowFilter.regexFilter("(?i)" + text.trim().toUpperCase()));
            andFilters.add(RowFilter.regexFilter(cmbTipo.getSelectedItem().toString()));
            sorter.setRowFilter(RowFilter.andFilter(andFilters));
        }
    }

    private void readAtividadePreparo() {
        DefaultTableModel model = (DefaultTableModel) tblAtividadePreparo.getModel();
        AtividadePreparoDAO atvprepDao = new AtividadePreparoDAO();
        model.setNumRows(0);
        for (AtividadePreparo atvprep : atvprepDao.readPedidos()) {
            model.addRow(new Object[]{
                atvprep.getAtividade_preparo_id(),
                DataHora.getStringDateTime(atvprep.getData_hora_registro()),
                (atvprep.getAnalise().getAnalise() == null ? "" : atvprep.getAnalise().getAnalise() + "   ")
                + (atvprep.getTipo_preparo() == null ? "" : atvprep.getTipo_preparo() + " - ")
                + (atvprep.getDescricao_preparo() == null ? "" : atvprep.getDescricao_preparo()),
                atvprep.getLote_preparo(),
                atvprep.getCromatografo().getSystem_name(),
                ((atvprep.getMetodologia().getMetodo_id() == 0) ? "MULTIPROPÓSITO"
                : atvprep.getMetodologia().getCod_metodo() + " - "
                + (atvprep.getMetodologia().getMetodo() == null ? "" : atvprep.getMetodologia().getMetodo())),
                atvprep.getQtd_preparo(),
                atvprep.getObs_preparo(),
                atvprep.getRetrabalho_preparo(),
                atvprep.getCategoria_preparo()
            });
        }
    }

    private void deletarDados(int id) {
        PedidoPreparoAcesso Acesso = new PedidoPreparoAcesso();
        if (Acesso.verificarDeletarDadosPedido()) {
            AtividadePreparo atvprep = new AtividadePreparo();
            AtividadePreparoDAO atvprepDAO = new AtividadePreparoDAO();
            try {
                int dialogResult = JOptionPane.showConfirmDialog(null,
                        "Realmente Deseja Excluir Esse Pedido?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (dialogResult == 0) {
                    atvprep.setAtividade_preparo_id(id);
                    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    FrmSalvar frmSalvar = new FrmSalvar(null, true);
                    frmSalvar.setVisible(true);
                    if (FrmSalvar.senha()) {
                        atvprepDAO.deleteAtividade(atvprep);
                    }
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao atulalizar dados: " + e);
            } finally {
                readAtividadePreparo();
            }
        }
    }

    private void carregarDados() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        int id = (Integer) tblAtividadePreparo.getValueAt(tblAtividadePreparo.getSelectedRow(), 0);
        if (("Análise").equals(tblAtividadePreparo.getValueAt(tblAtividadePreparo.getSelectedRow(), 9).toString())) {
            FrmAnalisePorLote frm = new FrmAnalisePorLote(null, true, id, true);
            frm.setVisible(true);
            readAtividadePreparo();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        if (("Soluções Reagentes").equals(tblAtividadePreparo.getValueAt(tblAtividadePreparo.getSelectedRow(), 9).toString())) {
            FrmSolucaoPreparo frm = new FrmSolucaoPreparo(null, true, id, true);
            frm.setVisible(true);
            readAtividadePreparo();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        if (("System Suitability").equals(tblAtividadePreparo.getValueAt(tblAtividadePreparo.getSelectedRow(), 9).toString())) {
            FrmSystemPreparo frm = new FrmSystemPreparo(null, true, id, true);
            frm.setVisible(true);
            readAtividadePreparo();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        if (("Atividade Geral").equals(tblAtividadePreparo.getValueAt(tblAtividadePreparo.getSelectedRow(), 9).toString())) {
            FrmAtividadeGeralPreparo frm = new FrmAtividadeGeralPreparo(null, true, id, true);
            frm.setVisible(true);
            readAtividadePreparo();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }
}
